// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthRequest struct {
	ClientNonce          []byte   `protobuf:"bytes,1,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_bb20ef7b16dadd40, []int{0}
}
func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (dst *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(dst, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetClientNonce() []byte {
	if m != nil {
		return m.ClientNonce
	}
	return nil
}

func (m *AuthRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type AuthResponse struct {
	ServerNonce          []byte   `protobuf:"bytes,1,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	Salt                 []byte   `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	Token                []byte   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_bb20ef7b16dadd40, []int{1}
}
func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (dst *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(dst, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetServerNonce() []byte {
	if m != nil {
		return m.ServerNonce
	}
	return nil
}

func (m *AuthResponse) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *AuthResponse) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

type Auth2Request struct {
	RandomPayload        []byte                   `protobuf:"bytes,1,opt,name=random_payload,json=randomPayload,proto3" json:"random_payload,omitempty"`
	Enc                  *Auth2Request_Encryption `protobuf:"bytes,2,opt,name=enc,proto3" json:"enc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Auth2Request) Reset()         { *m = Auth2Request{} }
func (m *Auth2Request) String() string { return proto.CompactTextString(m) }
func (*Auth2Request) ProtoMessage()    {}
func (*Auth2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_bb20ef7b16dadd40, []int{2}
}
func (m *Auth2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth2Request.Unmarshal(m, b)
}
func (m *Auth2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth2Request.Marshal(b, m, deterministic)
}
func (dst *Auth2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth2Request.Merge(dst, src)
}
func (m *Auth2Request) XXX_Size() int {
	return xxx_messageInfo_Auth2Request.Size(m)
}
func (m *Auth2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth2Request.DiscardUnknown(m)
}

var xxx_messageInfo_Auth2Request proto.InternalMessageInfo

func (m *Auth2Request) GetRandomPayload() []byte {
	if m != nil {
		return m.RandomPayload
	}
	return nil
}

func (m *Auth2Request) GetEnc() *Auth2Request_Encryption {
	if m != nil {
		return m.Enc
	}
	return nil
}

type Auth2Request_Encryption struct {
	Randomness           []byte   `protobuf:"bytes,1,opt,name=randomness,proto3" json:"randomness,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth2Request_Encryption) Reset()         { *m = Auth2Request_Encryption{} }
func (m *Auth2Request_Encryption) String() string { return proto.CompactTextString(m) }
func (*Auth2Request_Encryption) ProtoMessage()    {}
func (*Auth2Request_Encryption) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_bb20ef7b16dadd40, []int{2, 0}
}
func (m *Auth2Request_Encryption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth2Request_Encryption.Unmarshal(m, b)
}
func (m *Auth2Request_Encryption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth2Request_Encryption.Marshal(b, m, deterministic)
}
func (dst *Auth2Request_Encryption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth2Request_Encryption.Merge(dst, src)
}
func (m *Auth2Request_Encryption) XXX_Size() int {
	return xxx_messageInfo_Auth2Request_Encryption.Size(m)
}
func (m *Auth2Request_Encryption) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth2Request_Encryption.DiscardUnknown(m)
}

var xxx_messageInfo_Auth2Request_Encryption proto.InternalMessageInfo

func (m *Auth2Request_Encryption) GetRandomness() []byte {
	if m != nil {
		return m.Randomness
	}
	return nil
}

type Auth2Response struct {
	RandomPayload        []byte                    `protobuf:"bytes,1,opt,name=random_payload,json=randomPayload,proto3" json:"random_payload,omitempty"`
	Enc                  *Auth2Response_Encryption `protobuf:"bytes,2,opt,name=enc,proto3" json:"enc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Auth2Response) Reset()         { *m = Auth2Response{} }
func (m *Auth2Response) String() string { return proto.CompactTextString(m) }
func (*Auth2Response) ProtoMessage()    {}
func (*Auth2Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_bb20ef7b16dadd40, []int{3}
}
func (m *Auth2Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth2Response.Unmarshal(m, b)
}
func (m *Auth2Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth2Response.Marshal(b, m, deterministic)
}
func (dst *Auth2Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth2Response.Merge(dst, src)
}
func (m *Auth2Response) XXX_Size() int {
	return xxx_messageInfo_Auth2Response.Size(m)
}
func (m *Auth2Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth2Response.DiscardUnknown(m)
}

var xxx_messageInfo_Auth2Response proto.InternalMessageInfo

func (m *Auth2Response) GetRandomPayload() []byte {
	if m != nil {
		return m.RandomPayload
	}
	return nil
}

func (m *Auth2Response) GetEnc() *Auth2Response_Encryption {
	if m != nil {
		return m.Enc
	}
	return nil
}

type Auth2Response_Encryption struct {
	Randomness           []byte   `protobuf:"bytes,1,opt,name=randomness,proto3" json:"randomness,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth2Response_Encryption) Reset()         { *m = Auth2Response_Encryption{} }
func (m *Auth2Response_Encryption) String() string { return proto.CompactTextString(m) }
func (*Auth2Response_Encryption) ProtoMessage()    {}
func (*Auth2Response_Encryption) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_bb20ef7b16dadd40, []int{3, 0}
}
func (m *Auth2Response_Encryption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth2Response_Encryption.Unmarshal(m, b)
}
func (m *Auth2Response_Encryption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth2Response_Encryption.Marshal(b, m, deterministic)
}
func (dst *Auth2Response_Encryption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth2Response_Encryption.Merge(dst, src)
}
func (m *Auth2Response_Encryption) XXX_Size() int {
	return xxx_messageInfo_Auth2Response_Encryption.Size(m)
}
func (m *Auth2Response_Encryption) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth2Response_Encryption.DiscardUnknown(m)
}

var xxx_messageInfo_Auth2Response_Encryption proto.InternalMessageInfo

func (m *Auth2Response_Encryption) GetRandomness() []byte {
	if m != nil {
		return m.Randomness
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "api.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "api.AuthResponse")
	proto.RegisterType((*Auth2Request)(nil), "api.Auth2Request")
	proto.RegisterType((*Auth2Request_Encryption)(nil), "api.Auth2Request.Encryption")
	proto.RegisterType((*Auth2Response)(nil), "api.Auth2Response")
	proto.RegisterType((*Auth2Response_Encryption)(nil), "api.Auth2Response.Encryption")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_auth_bb20ef7b16dadd40) }

var fileDescriptor_auth_bb20ef7b16dadd40 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x40, 0xa9, 0xd5, 0x15, 0xa7, 0x5d, 0x0f, 0x41, 0xb0, 0x88, 0xca, 0x5a, 0x10, 0xf6, 0x20,
	0x15, 0xd6, 0x2f, 0xf0, 0xe0, 0x61, 0x2f, 0x22, 0xb9, 0x7a, 0x28, 0xb1, 0x1d, 0xd8, 0x60, 0x9d,
	0xc4, 0x24, 0x15, 0xf6, 0x3b, 0xc4, 0xff, 0x95, 0x66, 0x2a, 0xd6, 0x9b, 0xb0, 0xb7, 0xcc, 0x23,
	0xbc, 0x79, 0x21, 0x00, 0xaa, 0x0f, 0x9b, 0xca, 0x3a, 0x13, 0x8c, 0x48, 0x95, 0xd5, 0xe5, 0x1a,
	0xb2, 0xfb, 0x3e, 0x6c, 0x24, 0xbe, 0xf7, 0xe8, 0x83, 0xb8, 0x82, 0xbc, 0xe9, 0x34, 0x52, 0xa8,
	0xc9, 0x50, 0x83, 0x45, 0xb2, 0x48, 0x96, 0xb9, 0xcc, 0x98, 0x3d, 0x0e, 0x48, 0x9c, 0xc2, 0x61,
	0xef, 0xd1, 0xd5, 0xba, 0x2d, 0xf6, 0x16, 0xc9, 0xf2, 0x48, 0xce, 0x86, 0x71, 0xdd, 0x96, 0xcf,
	0x90, 0xb3, 0xca, 0x5b, 0x43, 0x1e, 0x07, 0x97, 0x47, 0xf7, 0x81, 0xee, 0xaf, 0x8b, 0x19, 0xbb,
	0x04, 0xec, 0x7b, 0xd5, 0x85, 0x28, 0xca, 0x65, 0x3c, 0x8b, 0x13, 0x38, 0x08, 0xe6, 0x15, 0xa9,
	0x48, 0x23, 0xe4, 0xa1, 0xfc, 0x4c, 0xd8, 0xbe, 0xfa, 0x29, 0xbd, 0x86, 0x63, 0xa7, 0xa8, 0x35,
	0x6f, 0xb5, 0x55, 0xdb, 0xce, 0xa8, 0x76, 0xf4, 0xcf, 0x99, 0x3e, 0x31, 0x14, 0x15, 0xa4, 0x48,
	0x4d, 0x5c, 0x90, 0xad, 0xce, 0x2b, 0x65, 0x75, 0x35, 0xd5, 0x54, 0x0f, 0xd4, 0xb8, 0xad, 0x0d,
	0xda, 0x90, 0x1c, 0x2e, 0x9e, 0xdd, 0x00, 0xfc, 0x22, 0x71, 0x09, 0xc0, 0x3a, 0x42, 0xef, 0xc7,
	0x05, 0x13, 0x52, 0x7e, 0x25, 0x30, 0x1f, 0x75, 0xe3, 0xa3, 0xff, 0x99, 0x75, 0x3b, 0xcd, 0xba,
	0x98, 0x66, 0xb1, 0x67, 0xb7, 0xae, 0x97, 0x59, 0xfc, 0xe1, 0xbb, 0xef, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xf4, 0xb3, 0x73, 0xcf, 0xef, 0x01, 0x00, 0x00,
}
