// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateAccountResponse_Error int32

const (
	CreateAccountResponse_NO_ERROR               CreateAccountResponse_Error = 0
	CreateAccountResponse_USER_NAME_ALREADY_USED CreateAccountResponse_Error = 1
	CreateAccountResponse_NOT_ENCRYPTED          CreateAccountResponse_Error = 2
)

var CreateAccountResponse_Error_name = map[int32]string{
	0: "NO_ERROR",
	1: "USER_NAME_ALREADY_USED",
	2: "NOT_ENCRYPTED",
}
var CreateAccountResponse_Error_value = map[string]int32{
	"NO_ERROR":               0,
	"USER_NAME_ALREADY_USED": 1,
	"NOT_ENCRYPTED":          2,
}

func (x CreateAccountResponse_Error) String() string {
	return proto.EnumName(CreateAccountResponse_Error_name, int32(x))
}
func (CreateAccountResponse_Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{3, 0}
}

type AuthRequest struct {
	// Types that are valid to be assigned to R:
	//	*AuthRequest_Auth
	//	*AuthRequest_AuthGuest
	//	*AuthRequest_Auth2
	//	*AuthRequest_RefreshToken
	//	*AuthRequest_RevokeSessions
	//	*AuthRequest_RevokeKeys
	//	*AuthRequest_CreateAccount
	//	*AuthRequest_ListKeys
	//	*AuthRequest_ListSessions
	R                    isAuthRequest_R `protobuf_oneof:"r"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{0}
}
func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (dst *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(dst, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

type isAuthRequest_R interface {
	isAuthRequest_R()
}

type AuthRequest_Auth struct {
	Auth *Auth1Request `protobuf:"bytes,1,opt,name=auth,proto3,oneof"`
}
type AuthRequest_AuthGuest struct {
	AuthGuest *Auth1GuestRequest `protobuf:"bytes,2,opt,name=auth_guest,json=authGuest,proto3,oneof"`
}
type AuthRequest_Auth2 struct {
	Auth2 *Auth2Request `protobuf:"bytes,3,opt,name=auth2,proto3,oneof"`
}
type AuthRequest_RefreshToken struct {
	RefreshToken *RefreshTokenRequest `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3,oneof"`
}
type AuthRequest_RevokeSessions struct {
	RevokeSessions *RevokeSessionsRequest `protobuf:"bytes,5,opt,name=revoke_sessions,json=revokeSessions,proto3,oneof"`
}
type AuthRequest_RevokeKeys struct {
	RevokeKeys *RevokeKeysRequest `protobuf:"bytes,6,opt,name=revoke_keys,json=revokeKeys,proto3,oneof"`
}
type AuthRequest_CreateAccount struct {
	CreateAccount *CreateAccountRequest `protobuf:"bytes,7,opt,name=create_account,json=createAccount,proto3,oneof"`
}
type AuthRequest_ListKeys struct {
	ListKeys *ListKeys `protobuf:"bytes,8,opt,name=list_keys,json=listKeys,proto3,oneof"`
}
type AuthRequest_ListSessions struct {
	ListSessions *ListSessions `protobuf:"bytes,9,opt,name=list_sessions,json=listSessions,proto3,oneof"`
}

func (*AuthRequest_Auth) isAuthRequest_R()           {}
func (*AuthRequest_AuthGuest) isAuthRequest_R()      {}
func (*AuthRequest_Auth2) isAuthRequest_R()          {}
func (*AuthRequest_RefreshToken) isAuthRequest_R()   {}
func (*AuthRequest_RevokeSessions) isAuthRequest_R() {}
func (*AuthRequest_RevokeKeys) isAuthRequest_R()     {}
func (*AuthRequest_CreateAccount) isAuthRequest_R()  {}
func (*AuthRequest_ListKeys) isAuthRequest_R()       {}
func (*AuthRequest_ListSessions) isAuthRequest_R()   {}

func (m *AuthRequest) GetR() isAuthRequest_R {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *AuthRequest) GetAuth() *Auth1Request {
	if x, ok := m.GetR().(*AuthRequest_Auth); ok {
		return x.Auth
	}
	return nil
}

func (m *AuthRequest) GetAuthGuest() *Auth1GuestRequest {
	if x, ok := m.GetR().(*AuthRequest_AuthGuest); ok {
		return x.AuthGuest
	}
	return nil
}

func (m *AuthRequest) GetAuth2() *Auth2Request {
	if x, ok := m.GetR().(*AuthRequest_Auth2); ok {
		return x.Auth2
	}
	return nil
}

func (m *AuthRequest) GetRefreshToken() *RefreshTokenRequest {
	if x, ok := m.GetR().(*AuthRequest_RefreshToken); ok {
		return x.RefreshToken
	}
	return nil
}

func (m *AuthRequest) GetRevokeSessions() *RevokeSessionsRequest {
	if x, ok := m.GetR().(*AuthRequest_RevokeSessions); ok {
		return x.RevokeSessions
	}
	return nil
}

func (m *AuthRequest) GetRevokeKeys() *RevokeKeysRequest {
	if x, ok := m.GetR().(*AuthRequest_RevokeKeys); ok {
		return x.RevokeKeys
	}
	return nil
}

func (m *AuthRequest) GetCreateAccount() *CreateAccountRequest {
	if x, ok := m.GetR().(*AuthRequest_CreateAccount); ok {
		return x.CreateAccount
	}
	return nil
}

func (m *AuthRequest) GetListKeys() *ListKeys {
	if x, ok := m.GetR().(*AuthRequest_ListKeys); ok {
		return x.ListKeys
	}
	return nil
}

func (m *AuthRequest) GetListSessions() *ListSessions {
	if x, ok := m.GetR().(*AuthRequest_ListSessions); ok {
		return x.ListSessions
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*AuthRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _AuthRequest_OneofMarshaler, _AuthRequest_OneofUnmarshaler, _AuthRequest_OneofSizer, []interface{}{
		(*AuthRequest_Auth)(nil),
		(*AuthRequest_AuthGuest)(nil),
		(*AuthRequest_Auth2)(nil),
		(*AuthRequest_RefreshToken)(nil),
		(*AuthRequest_RevokeSessions)(nil),
		(*AuthRequest_RevokeKeys)(nil),
		(*AuthRequest_CreateAccount)(nil),
		(*AuthRequest_ListKeys)(nil),
		(*AuthRequest_ListSessions)(nil),
	}
}

func _AuthRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*AuthRequest)
	// r
	switch x := m.R.(type) {
	case *AuthRequest_Auth:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Auth); err != nil {
			return err
		}
	case *AuthRequest_AuthGuest:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AuthGuest); err != nil {
			return err
		}
	case *AuthRequest_Auth2:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Auth2); err != nil {
			return err
		}
	case *AuthRequest_RefreshToken:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RefreshToken); err != nil {
			return err
		}
	case *AuthRequest_RevokeSessions:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RevokeSessions); err != nil {
			return err
		}
	case *AuthRequest_RevokeKeys:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RevokeKeys); err != nil {
			return err
		}
	case *AuthRequest_CreateAccount:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CreateAccount); err != nil {
			return err
		}
	case *AuthRequest_ListKeys:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ListKeys); err != nil {
			return err
		}
	case *AuthRequest_ListSessions:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ListSessions); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("AuthRequest.R has unexpected type %T", x)
	}
	return nil
}

func _AuthRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*AuthRequest)
	switch tag {
	case 1: // r.auth
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Auth1Request)
		err := b.DecodeMessage(msg)
		m.R = &AuthRequest_Auth{msg}
		return true, err
	case 2: // r.auth_guest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Auth1GuestRequest)
		err := b.DecodeMessage(msg)
		m.R = &AuthRequest_AuthGuest{msg}
		return true, err
	case 3: // r.auth2
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Auth2Request)
		err := b.DecodeMessage(msg)
		m.R = &AuthRequest_Auth2{msg}
		return true, err
	case 4: // r.refresh_token
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RefreshTokenRequest)
		err := b.DecodeMessage(msg)
		m.R = &AuthRequest_RefreshToken{msg}
		return true, err
	case 5: // r.revoke_sessions
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RevokeSessionsRequest)
		err := b.DecodeMessage(msg)
		m.R = &AuthRequest_RevokeSessions{msg}
		return true, err
	case 6: // r.revoke_keys
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RevokeKeysRequest)
		err := b.DecodeMessage(msg)
		m.R = &AuthRequest_RevokeKeys{msg}
		return true, err
	case 7: // r.create_account
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreateAccountRequest)
		err := b.DecodeMessage(msg)
		m.R = &AuthRequest_CreateAccount{msg}
		return true, err
	case 8: // r.list_keys
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ListKeys)
		err := b.DecodeMessage(msg)
		m.R = &AuthRequest_ListKeys{msg}
		return true, err
	case 9: // r.list_sessions
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ListSessions)
		err := b.DecodeMessage(msg)
		m.R = &AuthRequest_ListSessions{msg}
		return true, err
	default:
		return false, nil
	}
}

func _AuthRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*AuthRequest)
	// r
	switch x := m.R.(type) {
	case *AuthRequest_Auth:
		s := proto.Size(x.Auth)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AuthRequest_AuthGuest:
		s := proto.Size(x.AuthGuest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AuthRequest_Auth2:
		s := proto.Size(x.Auth2)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AuthRequest_RefreshToken:
		s := proto.Size(x.RefreshToken)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AuthRequest_RevokeSessions:
		s := proto.Size(x.RevokeSessions)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AuthRequest_RevokeKeys:
		s := proto.Size(x.RevokeKeys)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AuthRequest_CreateAccount:
		s := proto.Size(x.CreateAccount)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AuthRequest_ListKeys:
		s := proto.Size(x.ListKeys)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AuthRequest_ListSessions:
		s := proto.Size(x.ListSessions)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type AuthResponse struct {
	// Types that are valid to be assigned to R:
	//	*AuthResponse_Auth
	//	*AuthResponse_AuthGuest
	//	*AuthResponse_Auth2
	//	*AuthResponse_RefreshToken
	//	*AuthResponse_RevokeSessions
	//	*AuthResponse_RevokeKeys
	//	*AuthResponse_CreateAccount
	//	*AuthResponse_ListKeys
	//	*AuthResponse_ListSessions
	R                    isAuthResponse_R `protobuf_oneof:"r"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{1}
}
func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (dst *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(dst, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

type isAuthResponse_R interface {
	isAuthResponse_R()
}

type AuthResponse_Auth struct {
	Auth *Auth1Response `protobuf:"bytes,1,opt,name=auth,proto3,oneof"`
}
type AuthResponse_AuthGuest struct {
	AuthGuest *Auth1GuestResponse `protobuf:"bytes,2,opt,name=auth_guest,json=authGuest,proto3,oneof"`
}
type AuthResponse_Auth2 struct {
	Auth2 *Auth2Response `protobuf:"bytes,3,opt,name=auth2,proto3,oneof"`
}
type AuthResponse_RefreshToken struct {
	RefreshToken *RefreshTokenResponse `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3,oneof"`
}
type AuthResponse_RevokeSessions struct {
	RevokeSessions *RevokeSessionsResponse `protobuf:"bytes,5,opt,name=revoke_sessions,json=revokeSessions,proto3,oneof"`
}
type AuthResponse_RevokeKeys struct {
	RevokeKeys *RevokeKeysResponse `protobuf:"bytes,6,opt,name=revoke_keys,json=revokeKeys,proto3,oneof"`
}
type AuthResponse_CreateAccount struct {
	CreateAccount *CreateAccountResponse `protobuf:"bytes,7,opt,name=create_account,json=createAccount,proto3,oneof"`
}
type AuthResponse_ListKeys struct {
	ListKeys *KeyList `protobuf:"bytes,8,opt,name=list_keys,json=listKeys,proto3,oneof"`
}
type AuthResponse_ListSessions struct {
	ListSessions *SessionList `protobuf:"bytes,9,opt,name=list_sessions,json=listSessions,proto3,oneof"`
}

func (*AuthResponse_Auth) isAuthResponse_R()           {}
func (*AuthResponse_AuthGuest) isAuthResponse_R()      {}
func (*AuthResponse_Auth2) isAuthResponse_R()          {}
func (*AuthResponse_RefreshToken) isAuthResponse_R()   {}
func (*AuthResponse_RevokeSessions) isAuthResponse_R() {}
func (*AuthResponse_RevokeKeys) isAuthResponse_R()     {}
func (*AuthResponse_CreateAccount) isAuthResponse_R()  {}
func (*AuthResponse_ListKeys) isAuthResponse_R()       {}
func (*AuthResponse_ListSessions) isAuthResponse_R()   {}

func (m *AuthResponse) GetR() isAuthResponse_R {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *AuthResponse) GetAuth() *Auth1Response {
	if x, ok := m.GetR().(*AuthResponse_Auth); ok {
		return x.Auth
	}
	return nil
}

func (m *AuthResponse) GetAuthGuest() *Auth1GuestResponse {
	if x, ok := m.GetR().(*AuthResponse_AuthGuest); ok {
		return x.AuthGuest
	}
	return nil
}

func (m *AuthResponse) GetAuth2() *Auth2Response {
	if x, ok := m.GetR().(*AuthResponse_Auth2); ok {
		return x.Auth2
	}
	return nil
}

func (m *AuthResponse) GetRefreshToken() *RefreshTokenResponse {
	if x, ok := m.GetR().(*AuthResponse_RefreshToken); ok {
		return x.RefreshToken
	}
	return nil
}

func (m *AuthResponse) GetRevokeSessions() *RevokeSessionsResponse {
	if x, ok := m.GetR().(*AuthResponse_RevokeSessions); ok {
		return x.RevokeSessions
	}
	return nil
}

func (m *AuthResponse) GetRevokeKeys() *RevokeKeysResponse {
	if x, ok := m.GetR().(*AuthResponse_RevokeKeys); ok {
		return x.RevokeKeys
	}
	return nil
}

func (m *AuthResponse) GetCreateAccount() *CreateAccountResponse {
	if x, ok := m.GetR().(*AuthResponse_CreateAccount); ok {
		return x.CreateAccount
	}
	return nil
}

func (m *AuthResponse) GetListKeys() *KeyList {
	if x, ok := m.GetR().(*AuthResponse_ListKeys); ok {
		return x.ListKeys
	}
	return nil
}

func (m *AuthResponse) GetListSessions() *SessionList {
	if x, ok := m.GetR().(*AuthResponse_ListSessions); ok {
		return x.ListSessions
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*AuthResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _AuthResponse_OneofMarshaler, _AuthResponse_OneofUnmarshaler, _AuthResponse_OneofSizer, []interface{}{
		(*AuthResponse_Auth)(nil),
		(*AuthResponse_AuthGuest)(nil),
		(*AuthResponse_Auth2)(nil),
		(*AuthResponse_RefreshToken)(nil),
		(*AuthResponse_RevokeSessions)(nil),
		(*AuthResponse_RevokeKeys)(nil),
		(*AuthResponse_CreateAccount)(nil),
		(*AuthResponse_ListKeys)(nil),
		(*AuthResponse_ListSessions)(nil),
	}
}

func _AuthResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*AuthResponse)
	// r
	switch x := m.R.(type) {
	case *AuthResponse_Auth:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Auth); err != nil {
			return err
		}
	case *AuthResponse_AuthGuest:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AuthGuest); err != nil {
			return err
		}
	case *AuthResponse_Auth2:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Auth2); err != nil {
			return err
		}
	case *AuthResponse_RefreshToken:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RefreshToken); err != nil {
			return err
		}
	case *AuthResponse_RevokeSessions:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RevokeSessions); err != nil {
			return err
		}
	case *AuthResponse_RevokeKeys:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RevokeKeys); err != nil {
			return err
		}
	case *AuthResponse_CreateAccount:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CreateAccount); err != nil {
			return err
		}
	case *AuthResponse_ListKeys:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ListKeys); err != nil {
			return err
		}
	case *AuthResponse_ListSessions:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ListSessions); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("AuthResponse.R has unexpected type %T", x)
	}
	return nil
}

func _AuthResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*AuthResponse)
	switch tag {
	case 1: // r.auth
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Auth1Response)
		err := b.DecodeMessage(msg)
		m.R = &AuthResponse_Auth{msg}
		return true, err
	case 2: // r.auth_guest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Auth1GuestResponse)
		err := b.DecodeMessage(msg)
		m.R = &AuthResponse_AuthGuest{msg}
		return true, err
	case 3: // r.auth2
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Auth2Response)
		err := b.DecodeMessage(msg)
		m.R = &AuthResponse_Auth2{msg}
		return true, err
	case 4: // r.refresh_token
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RefreshTokenResponse)
		err := b.DecodeMessage(msg)
		m.R = &AuthResponse_RefreshToken{msg}
		return true, err
	case 5: // r.revoke_sessions
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RevokeSessionsResponse)
		err := b.DecodeMessage(msg)
		m.R = &AuthResponse_RevokeSessions{msg}
		return true, err
	case 6: // r.revoke_keys
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RevokeKeysResponse)
		err := b.DecodeMessage(msg)
		m.R = &AuthResponse_RevokeKeys{msg}
		return true, err
	case 7: // r.create_account
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreateAccountResponse)
		err := b.DecodeMessage(msg)
		m.R = &AuthResponse_CreateAccount{msg}
		return true, err
	case 8: // r.list_keys
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(KeyList)
		err := b.DecodeMessage(msg)
		m.R = &AuthResponse_ListKeys{msg}
		return true, err
	case 9: // r.list_sessions
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SessionList)
		err := b.DecodeMessage(msg)
		m.R = &AuthResponse_ListSessions{msg}
		return true, err
	default:
		return false, nil
	}
}

func _AuthResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*AuthResponse)
	// r
	switch x := m.R.(type) {
	case *AuthResponse_Auth:
		s := proto.Size(x.Auth)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AuthResponse_AuthGuest:
		s := proto.Size(x.AuthGuest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AuthResponse_Auth2:
		s := proto.Size(x.Auth2)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AuthResponse_RefreshToken:
		s := proto.Size(x.RefreshToken)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AuthResponse_RevokeSessions:
		s := proto.Size(x.RevokeSessions)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AuthResponse_RevokeKeys:
		s := proto.Size(x.RevokeKeys)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AuthResponse_CreateAccount:
		s := proto.Size(x.CreateAccount)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AuthResponse_ListKeys:
		s := proto.Size(x.ListKeys)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AuthResponse_ListSessions:
		s := proto.Size(x.ListSessions)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CreateAccountRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{2}
}
func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (dst *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(dst, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateAccountResponse struct {
	Success              bool                        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                CreateAccountResponse_Error `protobuf:"varint,2,opt,name=error,proto3,enum=api.CreateAccountResponse_Error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{3}
}
func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (dst *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(dst, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateAccountResponse) GetError() CreateAccountResponse_Error {
	if m != nil {
		return m.Error
	}
	return CreateAccountResponse_NO_ERROR
}

type Auth1Request struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Types that are valid to be assigned to A:
	//	*Auth1Request_Password_
	//	*Auth1Request_PubKey_
	A                    isAuth1Request_A `protobuf_oneof:"a"`
	DeviceType           []byte           `protobuf:"bytes,4,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Auth1Request) Reset()         { *m = Auth1Request{} }
func (m *Auth1Request) String() string { return proto.CompactTextString(m) }
func (*Auth1Request) ProtoMessage()    {}
func (*Auth1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{4}
}
func (m *Auth1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth1Request.Unmarshal(m, b)
}
func (m *Auth1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth1Request.Marshal(b, m, deterministic)
}
func (dst *Auth1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth1Request.Merge(dst, src)
}
func (m *Auth1Request) XXX_Size() int {
	return xxx_messageInfo_Auth1Request.Size(m)
}
func (m *Auth1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth1Request.DiscardUnknown(m)
}

var xxx_messageInfo_Auth1Request proto.InternalMessageInfo

type isAuth1Request_A interface {
	isAuth1Request_A()
}

type Auth1Request_Password_ struct {
	Password *Auth1Request_Password `protobuf:"bytes,2,opt,name=password,proto3,oneof"`
}
type Auth1Request_PubKey_ struct {
	PubKey *Auth1Request_PubKey `protobuf:"bytes,3,opt,name=pub_key,json=pubKey,proto3,oneof"`
}

func (*Auth1Request_Password_) isAuth1Request_A() {}
func (*Auth1Request_PubKey_) isAuth1Request_A()   {}

func (m *Auth1Request) GetA() isAuth1Request_A {
	if m != nil {
		return m.A
	}
	return nil
}

func (m *Auth1Request) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Auth1Request) GetPassword() *Auth1Request_Password {
	if x, ok := m.GetA().(*Auth1Request_Password_); ok {
		return x.Password
	}
	return nil
}

func (m *Auth1Request) GetPubKey() *Auth1Request_PubKey {
	if x, ok := m.GetA().(*Auth1Request_PubKey_); ok {
		return x.PubKey
	}
	return nil
}

func (m *Auth1Request) GetDeviceType() []byte {
	if m != nil {
		return m.DeviceType
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Auth1Request) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Auth1Request_OneofMarshaler, _Auth1Request_OneofUnmarshaler, _Auth1Request_OneofSizer, []interface{}{
		(*Auth1Request_Password_)(nil),
		(*Auth1Request_PubKey_)(nil),
	}
}

func _Auth1Request_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Auth1Request)
	// a
	switch x := m.A.(type) {
	case *Auth1Request_Password_:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Password); err != nil {
			return err
		}
	case *Auth1Request_PubKey_:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PubKey); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Auth1Request.A has unexpected type %T", x)
	}
	return nil
}

func _Auth1Request_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Auth1Request)
	switch tag {
	case 2: // a.password
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Auth1Request_Password)
		err := b.DecodeMessage(msg)
		m.A = &Auth1Request_Password_{msg}
		return true, err
	case 3: // a.pub_key
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Auth1Request_PubKey)
		err := b.DecodeMessage(msg)
		m.A = &Auth1Request_PubKey_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Auth1Request_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Auth1Request)
	// a
	switch x := m.A.(type) {
	case *Auth1Request_Password_:
		s := proto.Size(x.Password)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Auth1Request_PubKey_:
		s := proto.Size(x.PubKey)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Auth1Request_Password struct {
	ClientNonce          []byte   `protobuf:"bytes,1,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth1Request_Password) Reset()         { *m = Auth1Request_Password{} }
func (m *Auth1Request_Password) String() string { return proto.CompactTextString(m) }
func (*Auth1Request_Password) ProtoMessage()    {}
func (*Auth1Request_Password) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{4, 0}
}
func (m *Auth1Request_Password) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth1Request_Password.Unmarshal(m, b)
}
func (m *Auth1Request_Password) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth1Request_Password.Marshal(b, m, deterministic)
}
func (dst *Auth1Request_Password) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth1Request_Password.Merge(dst, src)
}
func (m *Auth1Request_Password) XXX_Size() int {
	return xxx_messageInfo_Auth1Request_Password.Size(m)
}
func (m *Auth1Request_Password) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth1Request_Password.DiscardUnknown(m)
}

var xxx_messageInfo_Auth1Request_Password proto.InternalMessageInfo

func (m *Auth1Request_Password) GetClientNonce() []byte {
	if m != nil {
		return m.ClientNonce
	}
	return nil
}

type Auth1Request_PubKey struct {
	EccPub               []byte   `protobuf:"bytes,1,opt,name=ecc_pub,json=eccPub,proto3" json:"ecc_pub,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth1Request_PubKey) Reset()         { *m = Auth1Request_PubKey{} }
func (m *Auth1Request_PubKey) String() string { return proto.CompactTextString(m) }
func (*Auth1Request_PubKey) ProtoMessage()    {}
func (*Auth1Request_PubKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{4, 1}
}
func (m *Auth1Request_PubKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth1Request_PubKey.Unmarshal(m, b)
}
func (m *Auth1Request_PubKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth1Request_PubKey.Marshal(b, m, deterministic)
}
func (dst *Auth1Request_PubKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth1Request_PubKey.Merge(dst, src)
}
func (m *Auth1Request_PubKey) XXX_Size() int {
	return xxx_messageInfo_Auth1Request_PubKey.Size(m)
}
func (m *Auth1Request_PubKey) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth1Request_PubKey.DiscardUnknown(m)
}

var xxx_messageInfo_Auth1Request_PubKey proto.InternalMessageInfo

func (m *Auth1Request_PubKey) GetEccPub() []byte {
	if m != nil {
		return m.EccPub
	}
	return nil
}

type Auth1Response struct {
	// new session token used to identify this session
	Token []byte `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// info used to authenticate this session
	//
	// Types that are valid to be assigned to A:
	//	*Auth1Response_Password_
	//	*Auth1Response_PubKey_
	A                    isAuth1Response_A `protobuf_oneof:"a"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Auth1Response) Reset()         { *m = Auth1Response{} }
func (m *Auth1Response) String() string { return proto.CompactTextString(m) }
func (*Auth1Response) ProtoMessage()    {}
func (*Auth1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{5}
}
func (m *Auth1Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth1Response.Unmarshal(m, b)
}
func (m *Auth1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth1Response.Marshal(b, m, deterministic)
}
func (dst *Auth1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth1Response.Merge(dst, src)
}
func (m *Auth1Response) XXX_Size() int {
	return xxx_messageInfo_Auth1Response.Size(m)
}
func (m *Auth1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth1Response.DiscardUnknown(m)
}

var xxx_messageInfo_Auth1Response proto.InternalMessageInfo

type isAuth1Response_A interface {
	isAuth1Response_A()
}

type Auth1Response_Password_ struct {
	Password *Auth1Response_Password `protobuf:"bytes,2,opt,name=password,proto3,oneof"`
}
type Auth1Response_PubKey_ struct {
	PubKey *Auth1Response_PubKey `protobuf:"bytes,3,opt,name=pub_key,json=pubKey,proto3,oneof"`
}

func (*Auth1Response_Password_) isAuth1Response_A() {}
func (*Auth1Response_PubKey_) isAuth1Response_A()   {}

func (m *Auth1Response) GetA() isAuth1Response_A {
	if m != nil {
		return m.A
	}
	return nil
}

func (m *Auth1Response) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *Auth1Response) GetPassword() *Auth1Response_Password {
	if x, ok := m.GetA().(*Auth1Response_Password_); ok {
		return x.Password
	}
	return nil
}

func (m *Auth1Response) GetPubKey() *Auth1Response_PubKey {
	if x, ok := m.GetA().(*Auth1Response_PubKey_); ok {
		return x.PubKey
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Auth1Response) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Auth1Response_OneofMarshaler, _Auth1Response_OneofUnmarshaler, _Auth1Response_OneofSizer, []interface{}{
		(*Auth1Response_Password_)(nil),
		(*Auth1Response_PubKey_)(nil),
	}
}

func _Auth1Response_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Auth1Response)
	// a
	switch x := m.A.(type) {
	case *Auth1Response_Password_:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Password); err != nil {
			return err
		}
	case *Auth1Response_PubKey_:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PubKey); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Auth1Response.A has unexpected type %T", x)
	}
	return nil
}

func _Auth1Response_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Auth1Response)
	switch tag {
	case 2: // a.password
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Auth1Response_Password)
		err := b.DecodeMessage(msg)
		m.A = &Auth1Response_Password_{msg}
		return true, err
	case 3: // a.pub_key
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Auth1Response_PubKey)
		err := b.DecodeMessage(msg)
		m.A = &Auth1Response_PubKey_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Auth1Response_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Auth1Response)
	// a
	switch x := m.A.(type) {
	case *Auth1Response_Password_:
		s := proto.Size(x.Password)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Auth1Response_PubKey_:
		s := proto.Size(x.PubKey)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Auth1Response_Password struct {
	ServerNonce          []byte   `protobuf:"bytes,1,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	Salt                 []byte   `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth1Response_Password) Reset()         { *m = Auth1Response_Password{} }
func (m *Auth1Response_Password) String() string { return proto.CompactTextString(m) }
func (*Auth1Response_Password) ProtoMessage()    {}
func (*Auth1Response_Password) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{5, 0}
}
func (m *Auth1Response_Password) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth1Response_Password.Unmarshal(m, b)
}
func (m *Auth1Response_Password) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth1Response_Password.Marshal(b, m, deterministic)
}
func (dst *Auth1Response_Password) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth1Response_Password.Merge(dst, src)
}
func (m *Auth1Response_Password) XXX_Size() int {
	return xxx_messageInfo_Auth1Response_Password.Size(m)
}
func (m *Auth1Response_Password) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth1Response_Password.DiscardUnknown(m)
}

var xxx_messageInfo_Auth1Response_Password proto.InternalMessageInfo

func (m *Auth1Response_Password) GetServerNonce() []byte {
	if m != nil {
		return m.ServerNonce
	}
	return nil
}

func (m *Auth1Response_Password) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

type Auth1Response_PubKey struct {
	EccPub               []byte   `protobuf:"bytes,1,opt,name=ecc_pub,json=eccPub,proto3" json:"ecc_pub,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth1Response_PubKey) Reset()         { *m = Auth1Response_PubKey{} }
func (m *Auth1Response_PubKey) String() string { return proto.CompactTextString(m) }
func (*Auth1Response_PubKey) ProtoMessage()    {}
func (*Auth1Response_PubKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{5, 1}
}
func (m *Auth1Response_PubKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth1Response_PubKey.Unmarshal(m, b)
}
func (m *Auth1Response_PubKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth1Response_PubKey.Marshal(b, m, deterministic)
}
func (dst *Auth1Response_PubKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth1Response_PubKey.Merge(dst, src)
}
func (m *Auth1Response_PubKey) XXX_Size() int {
	return xxx_messageInfo_Auth1Response_PubKey.Size(m)
}
func (m *Auth1Response_PubKey) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth1Response_PubKey.DiscardUnknown(m)
}

var xxx_messageInfo_Auth1Response_PubKey proto.InternalMessageInfo

func (m *Auth1Response_PubKey) GetEccPub() []byte {
	if m != nil {
		return m.EccPub
	}
	return nil
}

type Auth1GuestRequest struct {
	GuestPub             []byte   `protobuf:"bytes,1,opt,name=guest_pub,json=guestPub,proto3" json:"guest_pub,omitempty"`
	GuestNonce           []byte   `protobuf:"bytes,2,opt,name=guest_nonce,json=guestNonce,proto3" json:"guest_nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth1GuestRequest) Reset()         { *m = Auth1GuestRequest{} }
func (m *Auth1GuestRequest) String() string { return proto.CompactTextString(m) }
func (*Auth1GuestRequest) ProtoMessage()    {}
func (*Auth1GuestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{6}
}
func (m *Auth1GuestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth1GuestRequest.Unmarshal(m, b)
}
func (m *Auth1GuestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth1GuestRequest.Marshal(b, m, deterministic)
}
func (dst *Auth1GuestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth1GuestRequest.Merge(dst, src)
}
func (m *Auth1GuestRequest) XXX_Size() int {
	return xxx_messageInfo_Auth1GuestRequest.Size(m)
}
func (m *Auth1GuestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth1GuestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Auth1GuestRequest proto.InternalMessageInfo

func (m *Auth1GuestRequest) GetGuestPub() []byte {
	if m != nil {
		return m.GuestPub
	}
	return nil
}

func (m *Auth1GuestRequest) GetGuestNonce() []byte {
	if m != nil {
		return m.GuestNonce
	}
	return nil
}

type Auth1GuestResponse struct {
	ServerPub            []byte   `protobuf:"bytes,1,opt,name=server_pub,json=serverPub,proto3" json:"server_pub,omitempty"`
	ServerNonce          []byte   `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	SessionToken         []byte   `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth1GuestResponse) Reset()         { *m = Auth1GuestResponse{} }
func (m *Auth1GuestResponse) String() string { return proto.CompactTextString(m) }
func (*Auth1GuestResponse) ProtoMessage()    {}
func (*Auth1GuestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{7}
}
func (m *Auth1GuestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth1GuestResponse.Unmarshal(m, b)
}
func (m *Auth1GuestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth1GuestResponse.Marshal(b, m, deterministic)
}
func (dst *Auth1GuestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth1GuestResponse.Merge(dst, src)
}
func (m *Auth1GuestResponse) XXX_Size() int {
	return xxx_messageInfo_Auth1GuestResponse.Size(m)
}
func (m *Auth1GuestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth1GuestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Auth1GuestResponse proto.InternalMessageInfo

func (m *Auth1GuestResponse) GetServerPub() []byte {
	if m != nil {
		return m.ServerPub
	}
	return nil
}

func (m *Auth1GuestResponse) GetServerNonce() []byte {
	if m != nil {
		return m.ServerNonce
	}
	return nil
}

func (m *Auth1GuestResponse) GetSessionToken() []byte {
	if m != nil {
		return m.SessionToken
	}
	return nil
}

// second set of messages to ensure credentials are good
type Auth2Request struct {
	EnableEncryption     bool     `protobuf:"varint,1,opt,name=enable_encryption,json=enableEncryption,proto3" json:"enable_encryption,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth2Request) Reset()         { *m = Auth2Request{} }
func (m *Auth2Request) String() string { return proto.CompactTextString(m) }
func (*Auth2Request) ProtoMessage()    {}
func (*Auth2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{8}
}
func (m *Auth2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth2Request.Unmarshal(m, b)
}
func (m *Auth2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth2Request.Marshal(b, m, deterministic)
}
func (dst *Auth2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth2Request.Merge(dst, src)
}
func (m *Auth2Request) XXX_Size() int {
	return xxx_messageInfo_Auth2Request.Size(m)
}
func (m *Auth2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth2Request.DiscardUnknown(m)
}

var xxx_messageInfo_Auth2Request proto.InternalMessageInfo

func (m *Auth2Request) GetEnableEncryption() bool {
	if m != nil {
		return m.EnableEncryption
	}
	return false
}

type Auth2Response struct {
	EncryptionEnabled    bool     `protobuf:"varint,1,opt,name=encryption_enabled,json=encryptionEnabled,proto3" json:"encryption_enabled,omitempty"`
	TokenExpiry          uint64   `protobuf:"varint,2,opt,name=token_expiry,json=tokenExpiry,proto3" json:"token_expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth2Response) Reset()         { *m = Auth2Response{} }
func (m *Auth2Response) String() string { return proto.CompactTextString(m) }
func (*Auth2Response) ProtoMessage()    {}
func (*Auth2Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{9}
}
func (m *Auth2Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth2Response.Unmarshal(m, b)
}
func (m *Auth2Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth2Response.Marshal(b, m, deterministic)
}
func (dst *Auth2Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth2Response.Merge(dst, src)
}
func (m *Auth2Response) XXX_Size() int {
	return xxx_messageInfo_Auth2Response.Size(m)
}
func (m *Auth2Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth2Response.DiscardUnknown(m)
}

var xxx_messageInfo_Auth2Response proto.InternalMessageInfo

func (m *Auth2Response) GetEncryptionEnabled() bool {
	if m != nil {
		return m.EncryptionEnabled
	}
	return false
}

func (m *Auth2Response) GetTokenExpiry() uint64 {
	if m != nil {
		return m.TokenExpiry
	}
	return 0
}

// generate a new token with new secret credentials
type RefreshTokenRequest struct {
	ClientInput          []byte   `protobuf:"bytes,1,opt,name=client_input,json=clientInput,proto3" json:"client_input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenRequest) Reset()         { *m = RefreshTokenRequest{} }
func (m *RefreshTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenRequest) ProtoMessage()    {}
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{10}
}
func (m *RefreshTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenRequest.Unmarshal(m, b)
}
func (m *RefreshTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenRequest.Marshal(b, m, deterministic)
}
func (dst *RefreshTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenRequest.Merge(dst, src)
}
func (m *RefreshTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenRequest.Size(m)
}
func (m *RefreshTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenRequest proto.InternalMessageInfo

func (m *RefreshTokenRequest) GetClientInput() []byte {
	if m != nil {
		return m.ClientInput
	}
	return nil
}

type RefreshTokenResponse struct {
	Token                []byte   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ServerInput          []byte   `protobuf:"bytes,2,opt,name=server_input,json=serverInput,proto3" json:"server_input,omitempty"`
	TokenExpiry          uint64   `protobuf:"varint,3,opt,name=token_expiry,json=tokenExpiry,proto3" json:"token_expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenResponse) Reset()         { *m = RefreshTokenResponse{} }
func (m *RefreshTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenResponse) ProtoMessage()    {}
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{11}
}
func (m *RefreshTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenResponse.Unmarshal(m, b)
}
func (m *RefreshTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenResponse.Marshal(b, m, deterministic)
}
func (dst *RefreshTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenResponse.Merge(dst, src)
}
func (m *RefreshTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenResponse.Size(m)
}
func (m *RefreshTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenResponse proto.InternalMessageInfo

func (m *RefreshTokenResponse) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *RefreshTokenResponse) GetServerInput() []byte {
	if m != nil {
		return m.ServerInput
	}
	return nil
}

func (m *RefreshTokenResponse) GetTokenExpiry() uint64 {
	if m != nil {
		return m.TokenExpiry
	}
	return 0
}

type RevokeSessionsRequest struct {
	Sessions             [][]byte `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeSessionsRequest) Reset()         { *m = RevokeSessionsRequest{} }
func (m *RevokeSessionsRequest) String() string { return proto.CompactTextString(m) }
func (*RevokeSessionsRequest) ProtoMessage()    {}
func (*RevokeSessionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{12}
}
func (m *RevokeSessionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeSessionsRequest.Unmarshal(m, b)
}
func (m *RevokeSessionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeSessionsRequest.Marshal(b, m, deterministic)
}
func (dst *RevokeSessionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeSessionsRequest.Merge(dst, src)
}
func (m *RevokeSessionsRequest) XXX_Size() int {
	return xxx_messageInfo_RevokeSessionsRequest.Size(m)
}
func (m *RevokeSessionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeSessionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeSessionsRequest proto.InternalMessageInfo

func (m *RevokeSessionsRequest) GetSessions() [][]byte {
	if m != nil {
		return m.Sessions
	}
	return nil
}

type RevokeSessionsResponse struct {
	Sessions             [][]byte `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Success              []bool   `protobuf:"varint,2,rep,packed,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeSessionsResponse) Reset()         { *m = RevokeSessionsResponse{} }
func (m *RevokeSessionsResponse) String() string { return proto.CompactTextString(m) }
func (*RevokeSessionsResponse) ProtoMessage()    {}
func (*RevokeSessionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{13}
}
func (m *RevokeSessionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeSessionsResponse.Unmarshal(m, b)
}
func (m *RevokeSessionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeSessionsResponse.Marshal(b, m, deterministic)
}
func (dst *RevokeSessionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeSessionsResponse.Merge(dst, src)
}
func (m *RevokeSessionsResponse) XXX_Size() int {
	return xxx_messageInfo_RevokeSessionsResponse.Size(m)
}
func (m *RevokeSessionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeSessionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeSessionsResponse proto.InternalMessageInfo

func (m *RevokeSessionsResponse) GetSessions() [][]byte {
	if m != nil {
		return m.Sessions
	}
	return nil
}

func (m *RevokeSessionsResponse) GetSuccess() []bool {
	if m != nil {
		return m.Success
	}
	return nil
}

type RevokeKeysRequest struct {
	Keys                 [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeKeysRequest) Reset()         { *m = RevokeKeysRequest{} }
func (m *RevokeKeysRequest) String() string { return proto.CompactTextString(m) }
func (*RevokeKeysRequest) ProtoMessage()    {}
func (*RevokeKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{14}
}
func (m *RevokeKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeKeysRequest.Unmarshal(m, b)
}
func (m *RevokeKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeKeysRequest.Marshal(b, m, deterministic)
}
func (dst *RevokeKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeKeysRequest.Merge(dst, src)
}
func (m *RevokeKeysRequest) XXX_Size() int {
	return xxx_messageInfo_RevokeKeysRequest.Size(m)
}
func (m *RevokeKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeKeysRequest proto.InternalMessageInfo

func (m *RevokeKeysRequest) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

type RevokeKeysResponse struct {
	Keys                 [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Success              []bool   `protobuf:"varint,2,rep,packed,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeKeysResponse) Reset()         { *m = RevokeKeysResponse{} }
func (m *RevokeKeysResponse) String() string { return proto.CompactTextString(m) }
func (*RevokeKeysResponse) ProtoMessage()    {}
func (*RevokeKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{15}
}
func (m *RevokeKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeKeysResponse.Unmarshal(m, b)
}
func (m *RevokeKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeKeysResponse.Marshal(b, m, deterministic)
}
func (dst *RevokeKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeKeysResponse.Merge(dst, src)
}
func (m *RevokeKeysResponse) XXX_Size() int {
	return xxx_messageInfo_RevokeKeysResponse.Size(m)
}
func (m *RevokeKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeKeysResponse proto.InternalMessageInfo

func (m *RevokeKeysResponse) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *RevokeKeysResponse) GetSuccess() []bool {
	if m != nil {
		return m.Success
	}
	return nil
}

type ListKeys struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListKeys) Reset()         { *m = ListKeys{} }
func (m *ListKeys) String() string { return proto.CompactTextString(m) }
func (*ListKeys) ProtoMessage()    {}
func (*ListKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{16}
}
func (m *ListKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListKeys.Unmarshal(m, b)
}
func (m *ListKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListKeys.Marshal(b, m, deterministic)
}
func (dst *ListKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListKeys.Merge(dst, src)
}
func (m *ListKeys) XXX_Size() int {
	return xxx_messageInfo_ListKeys.Size(m)
}
func (m *ListKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_ListKeys.DiscardUnknown(m)
}

var xxx_messageInfo_ListKeys proto.InternalMessageInfo

type KeyList struct {
	Keys                 [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	DeviceType           [][]byte `protobuf:"bytes,2,rep,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyList) Reset()         { *m = KeyList{} }
func (m *KeyList) String() string { return proto.CompactTextString(m) }
func (*KeyList) ProtoMessage()    {}
func (*KeyList) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{17}
}
func (m *KeyList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyList.Unmarshal(m, b)
}
func (m *KeyList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyList.Marshal(b, m, deterministic)
}
func (dst *KeyList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyList.Merge(dst, src)
}
func (m *KeyList) XXX_Size() int {
	return xxx_messageInfo_KeyList.Size(m)
}
func (m *KeyList) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyList.DiscardUnknown(m)
}

var xxx_messageInfo_KeyList proto.InternalMessageInfo

func (m *KeyList) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *KeyList) GetDeviceType() [][]byte {
	if m != nil {
		return m.DeviceType
	}
	return nil
}

type ListSessions struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSessions) Reset()         { *m = ListSessions{} }
func (m *ListSessions) String() string { return proto.CompactTextString(m) }
func (*ListSessions) ProtoMessage()    {}
func (*ListSessions) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{18}
}
func (m *ListSessions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSessions.Unmarshal(m, b)
}
func (m *ListSessions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSessions.Marshal(b, m, deterministic)
}
func (dst *ListSessions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSessions.Merge(dst, src)
}
func (m *ListSessions) XXX_Size() int {
	return xxx_messageInfo_ListSessions.Size(m)
}
func (m *ListSessions) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSessions.DiscardUnknown(m)
}

var xxx_messageInfo_ListSessions proto.InternalMessageInfo

type SessionList struct {
	Sessions             [][]byte `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	DeviceType           [][]byte `protobuf:"bytes,2,rep,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	Expiration           []uint64 `protobuf:"varint,3,rep,packed,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionList) Reset()         { *m = SessionList{} }
func (m *SessionList) String() string { return proto.CompactTextString(m) }
func (*SessionList) ProtoMessage()    {}
func (*SessionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_c5b33b636c78fb40, []int{19}
}
func (m *SessionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionList.Unmarshal(m, b)
}
func (m *SessionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionList.Marshal(b, m, deterministic)
}
func (dst *SessionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionList.Merge(dst, src)
}
func (m *SessionList) XXX_Size() int {
	return xxx_messageInfo_SessionList.Size(m)
}
func (m *SessionList) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionList.DiscardUnknown(m)
}

var xxx_messageInfo_SessionList proto.InternalMessageInfo

func (m *SessionList) GetSessions() [][]byte {
	if m != nil {
		return m.Sessions
	}
	return nil
}

func (m *SessionList) GetDeviceType() [][]byte {
	if m != nil {
		return m.DeviceType
	}
	return nil
}

func (m *SessionList) GetExpiration() []uint64 {
	if m != nil {
		return m.Expiration
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "api.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "api.AuthResponse")
	proto.RegisterType((*CreateAccountRequest)(nil), "api.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "api.CreateAccountResponse")
	proto.RegisterType((*Auth1Request)(nil), "api.Auth1Request")
	proto.RegisterType((*Auth1Request_Password)(nil), "api.Auth1Request.Password")
	proto.RegisterType((*Auth1Request_PubKey)(nil), "api.Auth1Request.PubKey")
	proto.RegisterType((*Auth1Response)(nil), "api.Auth1Response")
	proto.RegisterType((*Auth1Response_Password)(nil), "api.Auth1Response.Password")
	proto.RegisterType((*Auth1Response_PubKey)(nil), "api.Auth1Response.PubKey")
	proto.RegisterType((*Auth1GuestRequest)(nil), "api.Auth1GuestRequest")
	proto.RegisterType((*Auth1GuestResponse)(nil), "api.Auth1GuestResponse")
	proto.RegisterType((*Auth2Request)(nil), "api.Auth2Request")
	proto.RegisterType((*Auth2Response)(nil), "api.Auth2Response")
	proto.RegisterType((*RefreshTokenRequest)(nil), "api.RefreshTokenRequest")
	proto.RegisterType((*RefreshTokenResponse)(nil), "api.RefreshTokenResponse")
	proto.RegisterType((*RevokeSessionsRequest)(nil), "api.RevokeSessionsRequest")
	proto.RegisterType((*RevokeSessionsResponse)(nil), "api.RevokeSessionsResponse")
	proto.RegisterType((*RevokeKeysRequest)(nil), "api.RevokeKeysRequest")
	proto.RegisterType((*RevokeKeysResponse)(nil), "api.RevokeKeysResponse")
	proto.RegisterType((*ListKeys)(nil), "api.ListKeys")
	proto.RegisterType((*KeyList)(nil), "api.KeyList")
	proto.RegisterType((*ListSessions)(nil), "api.ListSessions")
	proto.RegisterType((*SessionList)(nil), "api.SessionList")
	proto.RegisterEnum("api.CreateAccountResponse_Error", CreateAccountResponse_Error_name, CreateAccountResponse_Error_value)
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_auth_c5b33b636c78fb40) }

var fileDescriptor_auth_c5b33b636c78fb40 = []byte{
	// 1028 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0x5f, 0x73, 0xdb, 0x44,
	0x10, 0x8f, 0xff, 0xdb, 0x6b, 0x39, 0xd8, 0x47, 0x9a, 0x28, 0xce, 0x00, 0xae, 0x78, 0x68, 0xa0,
	0xd4, 0x33, 0x4d, 0x18, 0x9a, 0xc2, 0x0c, 0xe0, 0x24, 0x82, 0x74, 0x52, 0x9c, 0x70, 0x49, 0x1f,
	0xfa, 0xa4, 0x91, 0xe5, 0x83, 0x88, 0x78, 0x24, 0xa1, 0x3f, 0x01, 0x0f, 0x4f, 0x7c, 0x81, 0x3e,
	0xf1, 0x3d, 0xf8, 0x8a, 0xcc, 0xed, 0xc9, 0xd2, 0xc9, 0xba, 0xa4, 0xbc, 0xe9, 0x76, 0x7f, 0xbf,
	0xbd, 0xdb, 0xbd, 0xdf, 0xed, 0x0a, 0xc0, 0x4e, 0xe2, 0x9b, 0x71, 0x10, 0xfa, 0xb1, 0x4f, 0x6a,
	0x76, 0xe0, 0x1a, 0xef, 0xea, 0xd0, 0x9d, 0x24, 0xf1, 0x0d, 0x65, 0xbf, 0x27, 0x2c, 0x8a, 0xc9,
	0x13, 0xa8, 0x73, 0x88, 0x5e, 0x19, 0x55, 0xf6, 0xbb, 0x07, 0x83, 0xb1, 0x1d, 0xb8, 0x63, 0xee,
	0x7f, 0x9e, 0x02, 0xce, 0x36, 0x28, 0x02, 0xc8, 0x0b, 0x11, 0xcb, 0xfa, 0x95, 0x5b, 0xf5, 0x2a,
	0xc2, 0xb7, 0x73, 0xf8, 0x8f, 0xdc, 0x9c, 0x73, 0x3a, 0x1c, 0x8b, 0x36, 0xf2, 0x19, 0x34, 0xf8,
	0xe2, 0x40, 0xaf, 0xad, 0x6d, 0x71, 0x90, 0xc3, 0x05, 0x82, 0x7c, 0x07, 0xbd, 0x90, 0xfd, 0x12,
	0xb2, 0xe8, 0xc6, 0x8a, 0xfd, 0x5b, 0xe6, 0xe9, 0x75, 0xa4, 0xe8, 0x48, 0xa1, 0xc2, 0x73, 0xcd,
	0x1d, 0x39, 0x53, 0x0b, 0x25, 0x33, 0x31, 0xe1, 0x83, 0x90, 0xdd, 0xf9, 0xb7, 0xcc, 0x8a, 0x58,
	0x14, 0xb9, 0xbe, 0x17, 0xe9, 0x0d, 0x0c, 0x31, 0x4c, 0x43, 0x70, 0xdf, 0x55, 0xea, 0xca, 0x83,
	0x6c, 0x86, 0x05, 0x07, 0x79, 0x09, 0xdd, 0x34, 0xcc, 0x2d, 0x5b, 0x46, 0x7a, 0x53, 0x4a, 0x56,
	0x84, 0x38, 0x67, 0x4b, 0x89, 0x0e, 0x61, 0x66, 0x24, 0xc7, 0xb0, 0xe9, 0x84, 0xcc, 0x8e, 0x99,
	0x65, 0x3b, 0x8e, 0x9f, 0x78, 0xb1, 0xde, 0x42, 0xf6, 0x2e, 0xb2, 0x4f, 0xd0, 0x35, 0x11, 0x9e,
	0x3c, 0x40, 0xcf, 0x91, 0xed, 0xe4, 0x0b, 0xe8, 0x2c, 0xdc, 0x28, 0x16, 0x9b, 0xb7, 0x91, 0xde,
	0x43, 0xfa, 0x6b, 0x37, 0x8a, 0xf9, 0x2e, 0x67, 0x1b, 0xb4, 0xbd, 0x48, 0xbf, 0xc9, 0x11, 0xf4,
	0x10, 0x9d, 0x65, 0xdc, 0x91, 0xea, 0xcc, 0x19, 0xab, 0xb4, 0x78, 0xb5, 0x16, 0xd2, 0xfa, 0xb8,
	0x06, 0x95, 0xd0, 0xf8, 0xa7, 0x0e, 0x9a, 0x10, 0x44, 0x14, 0xf8, 0x5e, 0xc4, 0xc8, 0x7e, 0x41,
	0x11, 0x44, 0x56, 0x84, 0x40, 0x64, 0x92, 0x38, 0x52, 0x48, 0x62, 0xa7, 0x24, 0x89, 0x8c, 0x24,
	0x69, 0xe2, 0xf3, 0xa2, 0x26, 0x88, 0xac, 0x89, 0x0c, 0x9f, 0x8a, 0xe2, 0x7b, 0xb5, 0x28, 0x76,
	0x15, 0xa2, 0xc8, 0xa8, 0x45, 0x55, 0xfc, 0x70, 0x9f, 0x2a, 0xf6, 0x94, 0xaa, 0xc8, 0xa2, 0xac,
	0xcb, 0xe2, 0x6b, 0x95, 0x2c, 0x76, 0x4a, 0xb2, 0xc8, 0xf8, 0xb2, 0x2e, 0x4e, 0xee, 0xd1, 0xc5,
	0x50, 0xa5, 0x8b, 0x2c, 0xc2, 0x9a, 0x30, 0x9e, 0x96, 0x85, 0xa1, 0x21, 0xff, 0x9c, 0x2d, 0xf9,
	0x4d, 0x17, 0x74, 0xf1, 0x42, 0xad, 0x8b, 0x3e, 0x12, 0xd2, 0x9c, 0x52, 0x92, 0x42, 0x16, 0xe7,
	0xb0, 0xa5, 0x12, 0x2b, 0xd9, 0x81, 0x56, 0x12, 0xb1, 0xd0, 0x72, 0xe7, 0x28, 0x90, 0x0e, 0x6d,
	0xf2, 0xe5, 0xab, 0x39, 0x19, 0x42, 0x3b, 0xb0, 0xa3, 0xe8, 0x0f, 0x3f, 0x9c, 0xa3, 0x14, 0x3a,
	0x34, 0x5b, 0x1b, 0xff, 0x56, 0xe0, 0x91, 0x32, 0x45, 0xa2, 0x43, 0x2b, 0x4a, 0x1c, 0x87, 0x45,
	0x11, 0x86, 0x6b, 0xd3, 0xd5, 0x92, 0x7c, 0x05, 0x0d, 0x16, 0x86, 0x7e, 0x88, 0xc1, 0x36, 0x0f,
	0x46, 0xf7, 0xd7, 0x69, 0x6c, 0x72, 0x1c, 0x15, 0x70, 0xe3, 0x14, 0x1a, 0xb8, 0x26, 0x1a, 0xb4,
	0xa7, 0x17, 0x96, 0x49, 0xe9, 0x05, 0xed, 0x6f, 0x90, 0x21, 0x6c, 0xbf, 0xb9, 0x32, 0xa9, 0x35,
	0x9d, 0xfc, 0x64, 0x5a, 0x93, 0xd7, 0xd4, 0x9c, 0x9c, 0xbe, 0xb5, 0xde, 0x5c, 0x99, 0xa7, 0xfd,
	0x0a, 0x19, 0x40, 0x6f, 0x7a, 0x71, 0x6d, 0x99, 0xd3, 0x13, 0xfa, 0xf6, 0xf2, 0xda, 0x3c, 0xed,
	0x57, 0x8d, 0x77, 0x55, 0xf1, 0x2a, 0x9e, 0xbf, 0x37, 0xef, 0xa3, 0xb5, 0xbc, 0x57, 0x57, 0x2a,
	0xb3, 0xc7, 0x97, 0x29, 0x82, 0x5f, 0xd0, 0x0a, 0x4d, 0x0e, 0xa1, 0x15, 0x24, 0x33, 0x7e, 0x99,
	0xe9, 0x33, 0xd0, 0x15, 0xc4, 0x64, 0x76, 0xce, 0x96, 0x67, 0x1b, 0xb4, 0x19, 0xe0, 0x17, 0xf9,
	0x04, 0xba, 0x73, 0x76, 0xe7, 0x3a, 0xcc, 0x8a, 0x97, 0x01, 0xc3, 0xb7, 0xa0, 0x51, 0x10, 0xa6,
	0xeb, 0x65, 0xc0, 0x86, 0xcf, 0xa0, 0xbd, 0xda, 0x8d, 0x3c, 0x06, 0xcd, 0x59, 0xb8, 0xcc, 0x8b,
	0x2d, 0xcf, 0xf7, 0x1c, 0x86, 0x27, 0xd7, 0x68, 0x57, 0xd8, 0xa6, 0xdc, 0x34, 0x7c, 0x0c, 0x4d,
	0xb1, 0x07, 0xcf, 0x90, 0x39, 0x8e, 0x15, 0x24, 0xb3, 0x14, 0xd7, 0x64, 0x8e, 0x73, 0x99, 0xcc,
	0xb8, 0x1e, 0x6c, 0xe3, 0xef, 0x2a, 0xf4, 0x0a, 0x5d, 0x80, 0x6c, 0x41, 0x43, 0xbc, 0x47, 0x81,
	0x16, 0x0b, 0xf2, 0xb2, 0x54, 0x8e, 0xbd, 0x72, 0x07, 0x51, 0xd7, 0xe3, 0xcb, 0xf5, 0x7a, 0xec,
	0xaa, 0x98, 0x6b, 0x05, 0x19, 0x4e, 0x8a, 0xf9, 0x46, 0x2c, 0xbc, 0x63, 0x61, 0x31, 0x5f, 0x61,
	0xc3, 0x7c, 0x09, 0x81, 0x7a, 0x64, 0x2f, 0x44, 0xb7, 0xd2, 0x28, 0x7e, 0xff, 0xef, 0x1a, 0xfc,
	0x0c, 0x83, 0xd2, 0xac, 0x23, 0x7b, 0xd0, 0xc1, 0xfe, 0x27, 0x91, 0xda, 0x68, 0xb8, 0x4c, 0x66,
	0xfc, 0xb6, 0x84, 0x53, 0x9c, 0x47, 0x6c, 0x0a, 0x68, 0xc2, 0xe3, 0x18, 0x7f, 0x01, 0x29, 0xf7,
	0x4a, 0xf2, 0x11, 0x40, 0x9a, 0x47, 0x1e, 0xb4, 0x23, 0x2c, 0x3c, 0xea, 0x7a, 0x9a, 0xd5, 0x72,
	0x9a, 0x9f, 0x42, 0x2f, 0x7d, 0xf7, 0x69, 0xd3, 0xac, 0x21, 0x46, 0x4b, 0x8d, 0xd8, 0x17, 0x8d,
	0x6f, 0x84, 0xc6, 0x57, 0x73, 0x98, 0x3c, 0x85, 0x01, 0xf3, 0xec, 0xd9, 0x82, 0x59, 0xcc, 0x73,
	0xc2, 0x65, 0x10, 0xbb, 0xbe, 0x97, 0x3e, 0xcb, 0xbe, 0x70, 0x98, 0x99, 0xdd, 0xb0, 0x85, 0x1e,
	0xb2, 0x86, 0x4d, 0x9e, 0x01, 0xc9, 0x69, 0x96, 0xc0, 0xcf, 0x53, 0xfa, 0x20, 0xf7, 0x98, 0xc2,
	0xc1, 0x93, 0xc0, 0x93, 0x59, 0xec, 0xcf, 0xc0, 0x0d, 0x97, 0x98, 0x44, 0x9d, 0x76, 0xd1, 0x66,
	0xa2, 0xc9, 0x38, 0x82, 0x0f, 0x15, 0x43, 0x5f, 0x52, 0xb5, 0xeb, 0x05, 0x49, 0x5c, 0x54, 0xf5,
	0x2b, 0x6e, 0x32, 0x42, 0xd8, 0x52, 0x4d, 0x86, 0x7b, 0x34, 0x9b, 0xd7, 0x53, 0x04, 0x2c, 0xd4,
	0x13, 0x03, 0x96, 0x4e, 0x5b, 0x2b, 0x9f, 0xf6, 0x10, 0x1e, 0x29, 0xff, 0x2f, 0x78, 0x67, 0xcc,
	0x7a, 0x70, 0x65, 0x54, 0xe3, 0x02, 0x59, 0xad, 0x8d, 0x29, 0x6c, 0xab, 0xc7, 0xcf, 0x43, 0x2c,
	0xb9, 0x6b, 0x56, 0x47, 0x35, 0xa9, 0x6b, 0x1a, 0x4f, 0x60, 0x50, 0xfa, 0x43, 0xe1, 0x9a, 0xc7,
	0x89, 0x21, 0xc2, 0xe0, 0xb7, 0x71, 0x0c, 0xa4, 0x3c, 0xb3, 0x54, 0xc8, 0x07, 0x36, 0x03, 0x68,
	0xaf, 0xfe, 0x48, 0x8c, 0x6f, 0xa1, 0x95, 0x0e, 0x21, 0x65, 0x90, 0xb5, 0xb6, 0x55, 0x45, 0x97,
	0xd4, 0xb6, 0x8c, 0x4d, 0xd0, 0xe4, 0x7f, 0x15, 0xe3, 0x37, 0xe8, 0x4a, 0x33, 0xea, 0xc1, 0x6a,
	0xbc, 0x2f, 0x36, 0xf9, 0x18, 0x00, 0xaf, 0xcd, 0x46, 0x41, 0xd7, 0x46, 0xb5, 0xfd, 0x3a, 0x95,
	0x2c, 0xb3, 0x26, 0xfe, 0x1f, 0x1f, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x45, 0x86, 0x27,
	0x2d, 0x0b, 0x00, 0x00,
}
