// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Type int32

const (
	Type_PAWN   Type = 0
	Type_ROOK   Type = 1
	Type_KNIGHT Type = 2
	Type_BISHOP Type = 3
	Type_QUEEN  Type = 4
	Type_KING   Type = 5
)

var Type_name = map[int32]string{
	0: "PAWN",
	1: "ROOK",
	2: "KNIGHT",
	3: "BISHOP",
	4: "QUEEN",
	5: "KING",
}
var Type_value = map[string]int32{
	"PAWN":   0,
	"ROOK":   1,
	"KNIGHT": 2,
	"BISHOP": 3,
	"QUEEN":  4,
	"KING":   5,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_728661d2c4e5cc68, []int{0}
}

type Position struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_728661d2c4e5cc68, []int{0}
}
func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (dst *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(dst, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Position) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Piece struct {
	Type                 Type      `protobuf:"varint,1,opt,name=type,proto3,enum=api.Type" json:"type,omitempty"`
	Position             *Position `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Piece) Reset()         { *m = Piece{} }
func (m *Piece) String() string { return proto.CompactTextString(m) }
func (*Piece) ProtoMessage()    {}
func (*Piece) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_728661d2c4e5cc68, []int{1}
}
func (m *Piece) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Piece.Unmarshal(m, b)
}
func (m *Piece) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Piece.Marshal(b, m, deterministic)
}
func (dst *Piece) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Piece.Merge(dst, src)
}
func (m *Piece) XXX_Size() int {
	return xxx_messageInfo_Piece.Size(m)
}
func (m *Piece) XXX_DiscardUnknown() {
	xxx_messageInfo_Piece.DiscardUnknown(m)
}

var xxx_messageInfo_Piece proto.InternalMessageInfo

func (m *Piece) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_PAWN
}

func (m *Piece) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func init() {
	proto.RegisterType((*Position)(nil), "api.Position")
	proto.RegisterType((*Piece)(nil), "api.Piece")
	proto.RegisterEnum("api.Type", Type_name, Type_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_common_728661d2c4e5cc68) }

var fileDescriptor_common_728661d2c4e5cc68 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x52, 0xe3,
	0xe2, 0x08, 0xc8, 0x2f, 0xce, 0x2c, 0xc9, 0xcc, 0xcf, 0x13, 0xe2, 0xe1, 0x62, 0xac, 0x90, 0x60,
	0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0xac, 0x00, 0xf1, 0x2a, 0x25, 0x98, 0x20, 0xbc, 0x4a, 0xa5,
	0x40, 0x2e, 0xd6, 0x80, 0xcc, 0xd4, 0xe4, 0x54, 0x21, 0x59, 0x2e, 0x96, 0x92, 0xca, 0x82, 0x54,
	0xb0, 0x3a, 0x3e, 0x23, 0x4e, 0xbd, 0xc4, 0x82, 0x4c, 0xbd, 0x90, 0xca, 0x82, 0xd4, 0x20, 0xb0,
	0xb0, 0x90, 0x26, 0x17, 0x47, 0x01, 0xd4, 0x3c, 0xb0, 0x66, 0x6e, 0x23, 0x5e, 0xb0, 0x12, 0x98,
	0x25, 0x41, 0x70, 0x69, 0x2d, 0x77, 0x2e, 0x16, 0x90, 0x46, 0x21, 0x0e, 0x2e, 0x96, 0x00, 0xc7,
	0x70, 0x3f, 0x01, 0x06, 0x10, 0x2b, 0xc8, 0xdf, 0xdf, 0x5b, 0x80, 0x51, 0x88, 0x8b, 0x8b, 0xcd,
	0xdb, 0xcf, 0xd3, 0xdd, 0x23, 0x44, 0x80, 0x09, 0xc4, 0x76, 0xf2, 0x0c, 0xf6, 0xf0, 0x0f, 0x10,
	0x60, 0x16, 0xe2, 0xe4, 0x62, 0x0d, 0x0c, 0x75, 0x75, 0xf5, 0x13, 0x60, 0x01, 0x29, 0xf6, 0xf6,
	0xf4, 0x73, 0x17, 0x60, 0x4d, 0x62, 0x03, 0xfb, 0xc7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x20,
	0xcd, 0xb9, 0xa8, 0xdf, 0x00, 0x00, 0x00,
}
