// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Side int32

const (
	Side_WHITE Side = 0
	Side_BLACK Side = 1
)

var Side_name = map[int32]string{
	0: "WHITE",
	1: "BLACK",
}
var Side_value = map[string]int32{
	"WHITE": 0,
	"BLACK": 1,
}

func (x Side) String() string {
	return proto.EnumName(Side_name, int32(x))
}
func (Side) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_aba9fdc210bccf18, []int{0}
}

type Type int32

const (
	Type_INVALID Type = 0
	Type_PAWN    Type = 1
	Type_ROOK    Type = 2
	Type_KNIGHT  Type = 3
	Type_BISHOP  Type = 4
	Type_QUEEN   Type = 5
	Type_KING    Type = 6
)

var Type_name = map[int32]string{
	0: "INVALID",
	1: "PAWN",
	2: "ROOK",
	3: "KNIGHT",
	4: "BISHOP",
	5: "QUEEN",
	6: "KING",
}
var Type_value = map[string]int32{
	"INVALID": 0,
	"PAWN":    1,
	"ROOK":    2,
	"KNIGHT":  3,
	"BISHOP":  4,
	"QUEEN":   5,
	"KING":    6,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_aba9fdc210bccf18, []int{1}
}

type Position struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_aba9fdc210bccf18, []int{0}
}
func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (dst *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(dst, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Position) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Piece struct {
	Type                 Type      `protobuf:"varint,1,opt,name=type,proto3,enum=api.Type" json:"type,omitempty"`
	Position             *Position `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Piece) Reset()         { *m = Piece{} }
func (m *Piece) String() string { return proto.CompactTextString(m) }
func (*Piece) ProtoMessage()    {}
func (*Piece) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_aba9fdc210bccf18, []int{1}
}
func (m *Piece) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Piece.Unmarshal(m, b)
}
func (m *Piece) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Piece.Marshal(b, m, deterministic)
}
func (dst *Piece) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Piece.Merge(dst, src)
}
func (m *Piece) XXX_Size() int {
	return xxx_messageInfo_Piece.Size(m)
}
func (m *Piece) XXX_DiscardUnknown() {
	xxx_messageInfo_Piece.DiscardUnknown(m)
}

var xxx_messageInfo_Piece proto.InternalMessageInfo

func (m *Piece) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_INVALID
}

func (m *Piece) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func init() {
	proto.RegisterType((*Position)(nil), "api.Position")
	proto.RegisterType((*Piece)(nil), "api.Piece")
	proto.RegisterEnum("api.Side", Side_name, Side_value)
	proto.RegisterEnum("api.Type", Type_name, Type_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_common_aba9fdc210bccf18) }

var fileDescriptor_common_aba9fdc210bccf18 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xeb, 0xd6, 0x09, 0xe9, 0xb5, 0xa0, 0xd3, 0x4d, 0x1d, 0x40, 0x42, 0x1d, 0x10, 0x74,
	0xc8, 0x50, 0x9e, 0x20, 0x85, 0xa8, 0xb1, 0x52, 0x39, 0x69, 0x1a, 0xe8, 0x5c, 0x8a, 0x07, 0x0f,
	0xad, 0x2d, 0xc8, 0x10, 0xbf, 0x3d, 0xb2, 0x81, 0x6e, 0xff, 0x6f, 0x7f, 0xf7, 0x9d, 0x0e, 0xa6,
	0x47, 0x73, 0x3a, 0x99, 0x73, 0x6a, 0xbf, 0x4c, 0x67, 0x68, 0x74, 0xb0, 0x7a, 0xfe, 0x00, 0x49,
	0x6d, 0xbe, 0x75, 0xa7, 0xcd, 0x99, 0xa6, 0xc0, 0xfa, 0x19, 0xbb, 0x67, 0x8f, 0x51, 0xc3, 0x7a,
	0xdf, 0xdc, 0x6c, 0xf8, 0xdb, 0xdc, 0x7c, 0x0b, 0x51, 0xad, 0xd5, 0x51, 0xd1, 0x1d, 0xf0, 0xce,
	0x59, 0x15, 0xb8, 0x9b, 0xe5, 0x38, 0x3d, 0x58, 0x9d, 0xb6, 0xce, 0xaa, 0x26, 0x3c, 0xd3, 0x13,
	0x24, 0xf6, 0xcf, 0x17, 0x86, 0x27, 0xcb, 0xeb, 0x80, 0xfc, 0x2f, 0x69, 0x2e, 0xdf, 0x8b, 0x5b,
	0xe0, 0x3b, 0xfd, 0xa9, 0x68, 0x0c, 0xd1, 0xbe, 0x10, 0x6d, 0x8e, 0x03, 0x1f, 0x57, 0x9b, 0xec,
	0xa5, 0x44, 0xb6, 0x68, 0x81, 0x7b, 0x2d, 0x4d, 0xe0, 0x4a, 0xc8, 0xf7, 0x6c, 0x23, 0x5e, 0x71,
	0x40, 0x09, 0xf0, 0x3a, 0xdb, 0x4b, 0x64, 0x3e, 0x35, 0x55, 0x55, 0xe2, 0x90, 0x00, 0xe2, 0x52,
	0x8a, 0x75, 0xd1, 0xe2, 0xc8, 0xe7, 0x95, 0xd8, 0x15, 0x55, 0x8d, 0xdc, 0xbb, 0xb6, 0x6f, 0x79,
	0x2e, 0x31, 0xf2, 0x70, 0x29, 0xe4, 0x1a, 0xe3, 0x8f, 0x38, 0x9c, 0xfe, 0xfc, 0x13, 0x00, 0x00,
	0xff, 0xff, 0xa5, 0x1d, 0xbe, 0xd6, 0x0a, 0x01, 0x00, 0x00,
}
