// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListGamesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGamesRequest) Reset()         { *m = ListGamesRequest{} }
func (m *ListGamesRequest) String() string { return proto.CompactTextString(m) }
func (*ListGamesRequest) ProtoMessage()    {}
func (*ListGamesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_c4e93f0efd6aa501, []int{0}
}
func (m *ListGamesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGamesRequest.Unmarshal(m, b)
}
func (m *ListGamesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGamesRequest.Marshal(b, m, deterministic)
}
func (dst *ListGamesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGamesRequest.Merge(dst, src)
}
func (m *ListGamesRequest) XXX_Size() int {
	return xxx_messageInfo_ListGamesRequest.Size(m)
}
func (m *ListGamesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGamesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListGamesRequest proto.InternalMessageInfo

type ListGamesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGamesResponse) Reset()         { *m = ListGamesResponse{} }
func (m *ListGamesResponse) String() string { return proto.CompactTextString(m) }
func (*ListGamesResponse) ProtoMessage()    {}
func (*ListGamesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_c4e93f0efd6aa501, []int{1}
}
func (m *ListGamesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGamesResponse.Unmarshal(m, b)
}
func (m *ListGamesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGamesResponse.Marshal(b, m, deterministic)
}
func (dst *ListGamesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGamesResponse.Merge(dst, src)
}
func (m *ListGamesResponse) XXX_Size() int {
	return xxx_messageInfo_ListGamesResponse.Size(m)
}
func (m *ListGamesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGamesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGamesResponse proto.InternalMessageInfo

type MoveRequest struct {
	GameId               []byte   `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Side                 Side     `protobuf:"varint,2,opt,name=side,proto3,enum=api.Side" json:"side,omitempty"`
	Move                 *Move    `protobuf:"bytes,3,opt,name=move,proto3" json:"move,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveRequest) Reset()         { *m = MoveRequest{} }
func (m *MoveRequest) String() string { return proto.CompactTextString(m) }
func (*MoveRequest) ProtoMessage()    {}
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_c4e93f0efd6aa501, []int{2}
}
func (m *MoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveRequest.Unmarshal(m, b)
}
func (m *MoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveRequest.Marshal(b, m, deterministic)
}
func (dst *MoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveRequest.Merge(dst, src)
}
func (m *MoveRequest) XXX_Size() int {
	return xxx_messageInfo_MoveRequest.Size(m)
}
func (m *MoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveRequest proto.InternalMessageInfo

func (m *MoveRequest) GetGameId() []byte {
	if m != nil {
		return m.GameId
	}
	return nil
}

func (m *MoveRequest) GetSide() Side {
	if m != nil {
		return m.Side
	}
	return Side_WHITE
}

func (m *MoveRequest) GetMove() *Move {
	if m != nil {
		return m.Move
	}
	return nil
}

type MoveResponse struct {
	IsValid              bool     `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveResponse) Reset()         { *m = MoveResponse{} }
func (m *MoveResponse) String() string { return proto.CompactTextString(m) }
func (*MoveResponse) ProtoMessage()    {}
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_c4e93f0efd6aa501, []int{3}
}
func (m *MoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveResponse.Unmarshal(m, b)
}
func (m *MoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveResponse.Marshal(b, m, deterministic)
}
func (dst *MoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveResponse.Merge(dst, src)
}
func (m *MoveResponse) XXX_Size() int {
	return xxx_messageInfo_MoveResponse.Size(m)
}
func (m *MoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoveResponse proto.InternalMessageInfo

func (m *MoveResponse) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

type GetBoardRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBoardRequest) Reset()         { *m = GetBoardRequest{} }
func (m *GetBoardRequest) String() string { return proto.CompactTextString(m) }
func (*GetBoardRequest) ProtoMessage()    {}
func (*GetBoardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_c4e93f0efd6aa501, []int{4}
}
func (m *GetBoardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBoardRequest.Unmarshal(m, b)
}
func (m *GetBoardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBoardRequest.Marshal(b, m, deterministic)
}
func (dst *GetBoardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBoardRequest.Merge(dst, src)
}
func (m *GetBoardRequest) XXX_Size() int {
	return xxx_messageInfo_GetBoardRequest.Size(m)
}
func (m *GetBoardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBoardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBoardRequest proto.InternalMessageInfo

type GetBoardResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBoardResponse) Reset()         { *m = GetBoardResponse{} }
func (m *GetBoardResponse) String() string { return proto.CompactTextString(m) }
func (*GetBoardResponse) ProtoMessage()    {}
func (*GetBoardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_c4e93f0efd6aa501, []int{5}
}
func (m *GetBoardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBoardResponse.Unmarshal(m, b)
}
func (m *GetBoardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBoardResponse.Marshal(b, m, deterministic)
}
func (dst *GetBoardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBoardResponse.Merge(dst, src)
}
func (m *GetBoardResponse) XXX_Size() int {
	return xxx_messageInfo_GetBoardResponse.Size(m)
}
func (m *GetBoardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBoardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBoardResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ListGamesRequest)(nil), "api.ListGamesRequest")
	proto.RegisterType((*ListGamesResponse)(nil), "api.ListGamesResponse")
	proto.RegisterType((*MoveRequest)(nil), "api.MoveRequest")
	proto.RegisterType((*MoveResponse)(nil), "api.MoveResponse")
	proto.RegisterType((*GetBoardRequest)(nil), "api.GetBoardRequest")
	proto.RegisterType((*GetBoardResponse)(nil), "api.GetBoardResponse")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_game_c4e93f0efd6aa501) }

var fileDescriptor_game_c4e93f0efd6aa501 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x59, 0x2b, 0x6d, 0x9d, 0x2e, 0xda, 0xc6, 0x83, 0x6b, 0x41, 0x58, 0x72, 0x5a, 0x2f,
	0x7b, 0xd0, 0x6f, 0xe0, 0xa5, 0x08, 0x7a, 0x89, 0xe0, 0xb5, 0x44, 0x33, 0xc8, 0x80, 0xe9, 0xc4,
	0x4e, 0xdc, 0xcf, 0x2f, 0xf9, 0x23, 0x7a, 0x7c, 0xbf, 0x17, 0xde, 0x2f, 0x03, 0xf0, 0x61, 0x3d,
	0x8e, 0xe1, 0xc8, 0x91, 0xd5, 0xcc, 0x06, 0xda, 0xb6, 0xef, 0xec, 0x3d, 0x1f, 0x0a, 0xda, 0x82,
	0xe7, 0xa9, 0xd6, 0x5a, 0xc1, 0xfa, 0x89, 0x24, 0xee, 0xac, 0x47, 0x31, 0xf8, 0xf5, 0x8d, 0x12,
	0xf5, 0x25, 0x6c, 0xfe, 0x31, 0x09, 0x7c, 0x10, 0xd4, 0x0e, 0x56, 0xcf, 0x3c, 0x61, 0x7d, 0xa3,
	0xae, 0x60, 0x91, 0x24, 0x7b, 0x72, 0x5d, 0xd3, 0x37, 0x43, 0x6b, 0xe6, 0x29, 0x3e, 0x3a, 0x75,
	0x03, 0xa7, 0x42, 0x0e, 0xbb, 0x93, 0xbe, 0x19, 0xce, 0xef, 0xce, 0x46, 0x1b, 0x68, 0x7c, 0x21,
	0x87, 0x26, 0xe3, 0x54, 0x27, 0x7b, 0x37, 0xeb, 0x9b, 0x61, 0x55, 0xeb, 0xbc, 0x9b, 0xb1, 0xbe,
	0x85, 0xb6, 0x58, 0x8a, 0x55, 0x5d, 0xc3, 0x92, 0x64, 0x3f, 0xd9, 0xcf, 0xea, 0x59, 0x9a, 0x05,
	0xc9, 0x6b, 0x8a, 0x7a, 0x03, 0x17, 0x3b, 0x8c, 0x0f, 0x6c, 0x8f, 0xee, 0xf7, 0xe3, 0x0a, 0xd6,
	0x7f, 0xa8, 0x2c, 0xbc, 0xcd, 0xf3, 0x9d, 0xf7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x15,
	0x2c, 0xa3, 0x14, 0x01, 0x00, 0x00,
}
