// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Header struct {
	Version              uint32   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Token                []byte   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ClientNonce          []byte   `protobuf:"bytes,3,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"`
	ServerNonce          []byte   `protobuf:"bytes,4,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	Hmac                 []byte   `protobuf:"bytes,5,opt,name=hmac,proto3" json:"hmac,omitempty"`
	Encrypted            bool     `protobuf:"varint,6,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c9abbffb60ef2fad, []int{0}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (dst *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(dst, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Header) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *Header) GetClientNonce() []byte {
	if m != nil {
		return m.ClientNonce
	}
	return nil
}

func (m *Header) GetServerNonce() []byte {
	if m != nil {
		return m.ServerNonce
	}
	return nil
}

func (m *Header) GetHmac() []byte {
	if m != nil {
		return m.Hmac
	}
	return nil
}

func (m *Header) GetEncrypted() bool {
	if m != nil {
		return m.Encrypted
	}
	return false
}

type Message struct {
	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*Message_EncPayload
	//	*Message_AuthReq
	//	*Message_AuthResp
	//	*Message_Auth2Req
	//	*Message_Auth2Resp
	//	*Message_MakeMoveReq
	//	*Message_MakeMoveResp
	//	*Message_BoardReq
	//	*Message_BoardResp
	Payload              isMessage_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c9abbffb60ef2fad, []int{1}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_EncPayload struct {
	EncPayload []byte `protobuf:"bytes,2,opt,name=enc_payload,json=encPayload,proto3,oneof"`
}
type Message_AuthReq struct {
	AuthReq *AuthRequest `protobuf:"bytes,3,opt,name=auth_req,json=authReq,proto3,oneof"`
}
type Message_AuthResp struct {
	AuthResp *AuthResponse `protobuf:"bytes,4,opt,name=auth_resp,json=authResp,proto3,oneof"`
}
type Message_Auth2Req struct {
	Auth2Req *Auth2Request `protobuf:"bytes,5,opt,name=auth2_req,json=auth2Req,proto3,oneof"`
}
type Message_Auth2Resp struct {
	Auth2Resp *Auth2Response `protobuf:"bytes,6,opt,name=auth2_resp,json=auth2Resp,proto3,oneof"`
}
type Message_MakeMoveReq struct {
	MakeMoveReq *MoveRequest `protobuf:"bytes,7,opt,name=make_move_req,json=makeMoveReq,proto3,oneof"`
}
type Message_MakeMoveResp struct {
	MakeMoveResp *MoveResponse `protobuf:"bytes,8,opt,name=make_move_resp,json=makeMoveResp,proto3,oneof"`
}
type Message_BoardReq struct {
	BoardReq *GetBoardRequest `protobuf:"bytes,9,opt,name=board_req,json=boardReq,proto3,oneof"`
}
type Message_BoardResp struct {
	BoardResp *GetBoardResponse `protobuf:"bytes,10,opt,name=board_resp,json=boardResp,proto3,oneof"`
}

func (*Message_EncPayload) isMessage_Payload()   {}
func (*Message_AuthReq) isMessage_Payload()      {}
func (*Message_AuthResp) isMessage_Payload()     {}
func (*Message_Auth2Req) isMessage_Payload()     {}
func (*Message_Auth2Resp) isMessage_Payload()    {}
func (*Message_MakeMoveReq) isMessage_Payload()  {}
func (*Message_MakeMoveResp) isMessage_Payload() {}
func (*Message_BoardReq) isMessage_Payload()     {}
func (*Message_BoardResp) isMessage_Payload()    {}

func (m *Message) GetPayload() isMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Message) GetEncPayload() []byte {
	if x, ok := m.GetPayload().(*Message_EncPayload); ok {
		return x.EncPayload
	}
	return nil
}

func (m *Message) GetAuthReq() *AuthRequest {
	if x, ok := m.GetPayload().(*Message_AuthReq); ok {
		return x.AuthReq
	}
	return nil
}

func (m *Message) GetAuthResp() *AuthResponse {
	if x, ok := m.GetPayload().(*Message_AuthResp); ok {
		return x.AuthResp
	}
	return nil
}

func (m *Message) GetAuth2Req() *Auth2Request {
	if x, ok := m.GetPayload().(*Message_Auth2Req); ok {
		return x.Auth2Req
	}
	return nil
}

func (m *Message) GetAuth2Resp() *Auth2Response {
	if x, ok := m.GetPayload().(*Message_Auth2Resp); ok {
		return x.Auth2Resp
	}
	return nil
}

func (m *Message) GetMakeMoveReq() *MoveRequest {
	if x, ok := m.GetPayload().(*Message_MakeMoveReq); ok {
		return x.MakeMoveReq
	}
	return nil
}

func (m *Message) GetMakeMoveResp() *MoveResponse {
	if x, ok := m.GetPayload().(*Message_MakeMoveResp); ok {
		return x.MakeMoveResp
	}
	return nil
}

func (m *Message) GetBoardReq() *GetBoardRequest {
	if x, ok := m.GetPayload().(*Message_BoardReq); ok {
		return x.BoardReq
	}
	return nil
}

func (m *Message) GetBoardResp() *GetBoardResponse {
	if x, ok := m.GetPayload().(*Message_BoardResp); ok {
		return x.BoardResp
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_OneofMarshaler, _Message_OneofUnmarshaler, _Message_OneofSizer, []interface{}{
		(*Message_EncPayload)(nil),
		(*Message_AuthReq)(nil),
		(*Message_AuthResp)(nil),
		(*Message_Auth2Req)(nil),
		(*Message_Auth2Resp)(nil),
		(*Message_MakeMoveReq)(nil),
		(*Message_MakeMoveResp)(nil),
		(*Message_BoardReq)(nil),
		(*Message_BoardResp)(nil),
	}
}

func _Message_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message)
	// payload
	switch x := m.Payload.(type) {
	case *Message_EncPayload:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.EncPayload)
	case *Message_AuthReq:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AuthReq); err != nil {
			return err
		}
	case *Message_AuthResp:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AuthResp); err != nil {
			return err
		}
	case *Message_Auth2Req:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Auth2Req); err != nil {
			return err
		}
	case *Message_Auth2Resp:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Auth2Resp); err != nil {
			return err
		}
	case *Message_MakeMoveReq:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MakeMoveReq); err != nil {
			return err
		}
	case *Message_MakeMoveResp:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MakeMoveResp); err != nil {
			return err
		}
	case *Message_BoardReq:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BoardReq); err != nil {
			return err
		}
	case *Message_BoardResp:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BoardResp); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message.Payload has unexpected type %T", x)
	}
	return nil
}

func _Message_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message)
	switch tag {
	case 2: // payload.enc_payload
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Payload = &Message_EncPayload{x}
		return true, err
	case 3: // payload.auth_req
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AuthRequest)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_AuthReq{msg}
		return true, err
	case 4: // payload.auth_resp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AuthResponse)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_AuthResp{msg}
		return true, err
	case 5: // payload.auth2_req
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Auth2Request)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_Auth2Req{msg}
		return true, err
	case 6: // payload.auth2_resp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Auth2Response)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_Auth2Resp{msg}
		return true, err
	case 7: // payload.make_move_req
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MoveRequest)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_MakeMoveReq{msg}
		return true, err
	case 8: // payload.make_move_resp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MoveResponse)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_MakeMoveResp{msg}
		return true, err
	case 9: // payload.board_req
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetBoardRequest)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_BoardReq{msg}
		return true, err
	case 10: // payload.board_resp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetBoardResponse)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_BoardResp{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message)
	// payload
	switch x := m.Payload.(type) {
	case *Message_EncPayload:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.EncPayload)))
		n += len(x.EncPayload)
	case *Message_AuthReq:
		s := proto.Size(x.AuthReq)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_AuthResp:
		s := proto.Size(x.AuthResp)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Auth2Req:
		s := proto.Size(x.Auth2Req)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Auth2Resp:
		s := proto.Size(x.Auth2Resp)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_MakeMoveReq:
		s := proto.Size(x.MakeMoveReq)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_MakeMoveResp:
		s := proto.Size(x.MakeMoveResp)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_BoardReq:
		s := proto.Size(x.BoardReq)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_BoardResp:
		s := proto.Size(x.BoardResp)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type AuthRequest struct {
	ClientNonce          []byte   `protobuf:"bytes,1,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c9abbffb60ef2fad, []int{2}
}
func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (dst *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(dst, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetClientNonce() []byte {
	if m != nil {
		return m.ClientNonce
	}
	return nil
}

func (m *AuthRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type AuthResponse struct {
	ServerNonce          []byte   `protobuf:"bytes,1,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	Salt                 []byte   `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	Token                []byte   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c9abbffb60ef2fad, []int{3}
}
func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (dst *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(dst, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetServerNonce() []byte {
	if m != nil {
		return m.ServerNonce
	}
	return nil
}

func (m *AuthResponse) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *AuthResponse) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

type Auth2Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth2Request) Reset()         { *m = Auth2Request{} }
func (m *Auth2Request) String() string { return proto.CompactTextString(m) }
func (*Auth2Request) ProtoMessage()    {}
func (*Auth2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c9abbffb60ef2fad, []int{4}
}
func (m *Auth2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth2Request.Unmarshal(m, b)
}
func (m *Auth2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth2Request.Marshal(b, m, deterministic)
}
func (dst *Auth2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth2Request.Merge(dst, src)
}
func (m *Auth2Request) XXX_Size() int {
	return xxx_messageInfo_Auth2Request.Size(m)
}
func (m *Auth2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth2Request.DiscardUnknown(m)
}

var xxx_messageInfo_Auth2Request proto.InternalMessageInfo

type Auth2Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth2Response) Reset()         { *m = Auth2Response{} }
func (m *Auth2Response) String() string { return proto.CompactTextString(m) }
func (*Auth2Response) ProtoMessage()    {}
func (*Auth2Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c9abbffb60ef2fad, []int{5}
}
func (m *Auth2Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth2Response.Unmarshal(m, b)
}
func (m *Auth2Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth2Response.Marshal(b, m, deterministic)
}
func (dst *Auth2Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth2Response.Merge(dst, src)
}
func (m *Auth2Response) XXX_Size() int {
	return xxx_messageInfo_Auth2Response.Size(m)
}
func (m *Auth2Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth2Response.DiscardUnknown(m)
}

var xxx_messageInfo_Auth2Response proto.InternalMessageInfo

type MoveRequest struct {
	Move                 *Move    `protobuf:"bytes,1,opt,name=move,proto3" json:"move,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveRequest) Reset()         { *m = MoveRequest{} }
func (m *MoveRequest) String() string { return proto.CompactTextString(m) }
func (*MoveRequest) ProtoMessage()    {}
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c9abbffb60ef2fad, []int{6}
}
func (m *MoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveRequest.Unmarshal(m, b)
}
func (m *MoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveRequest.Marshal(b, m, deterministic)
}
func (dst *MoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveRequest.Merge(dst, src)
}
func (m *MoveRequest) XXX_Size() int {
	return xxx_messageInfo_MoveRequest.Size(m)
}
func (m *MoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveRequest proto.InternalMessageInfo

func (m *MoveRequest) GetMove() *Move {
	if m != nil {
		return m.Move
	}
	return nil
}

type MoveResponse struct {
	IsValid              bool     `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveResponse) Reset()         { *m = MoveResponse{} }
func (m *MoveResponse) String() string { return proto.CompactTextString(m) }
func (*MoveResponse) ProtoMessage()    {}
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c9abbffb60ef2fad, []int{7}
}
func (m *MoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveResponse.Unmarshal(m, b)
}
func (m *MoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveResponse.Marshal(b, m, deterministic)
}
func (dst *MoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveResponse.Merge(dst, src)
}
func (m *MoveResponse) XXX_Size() int {
	return xxx_messageInfo_MoveResponse.Size(m)
}
func (m *MoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoveResponse proto.InternalMessageInfo

func (m *MoveResponse) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

type GetBoardRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBoardRequest) Reset()         { *m = GetBoardRequest{} }
func (m *GetBoardRequest) String() string { return proto.CompactTextString(m) }
func (*GetBoardRequest) ProtoMessage()    {}
func (*GetBoardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c9abbffb60ef2fad, []int{8}
}
func (m *GetBoardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBoardRequest.Unmarshal(m, b)
}
func (m *GetBoardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBoardRequest.Marshal(b, m, deterministic)
}
func (dst *GetBoardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBoardRequest.Merge(dst, src)
}
func (m *GetBoardRequest) XXX_Size() int {
	return xxx_messageInfo_GetBoardRequest.Size(m)
}
func (m *GetBoardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBoardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBoardRequest proto.InternalMessageInfo

type GetBoardResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBoardResponse) Reset()         { *m = GetBoardResponse{} }
func (m *GetBoardResponse) String() string { return proto.CompactTextString(m) }
func (*GetBoardResponse) ProtoMessage()    {}
func (*GetBoardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c9abbffb60ef2fad, []int{9}
}
func (m *GetBoardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBoardResponse.Unmarshal(m, b)
}
func (m *GetBoardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBoardResponse.Marshal(b, m, deterministic)
}
func (dst *GetBoardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBoardResponse.Merge(dst, src)
}
func (m *GetBoardResponse) XXX_Size() int {
	return xxx_messageInfo_GetBoardResponse.Size(m)
}
func (m *GetBoardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBoardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBoardResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Header)(nil), "api.Header")
	proto.RegisterType((*Message)(nil), "api.Message")
	proto.RegisterType((*AuthRequest)(nil), "api.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "api.AuthResponse")
	proto.RegisterType((*Auth2Request)(nil), "api.Auth2Request")
	proto.RegisterType((*Auth2Response)(nil), "api.Auth2Response")
	proto.RegisterType((*MoveRequest)(nil), "api.MoveRequest")
	proto.RegisterType((*MoveResponse)(nil), "api.MoveResponse")
	proto.RegisterType((*GetBoardRequest)(nil), "api.GetBoardRequest")
	proto.RegisterType((*GetBoardResponse)(nil), "api.GetBoardResponse")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_c9abbffb60ef2fad) }

var fileDescriptor_message_c9abbffb60ef2fad = []byte{
	// 522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0x4f, 0x6f, 0x9b, 0x4e,
	0x10, 0x35, 0x3f, 0xff, 0x01, 0x06, 0x3b, 0x7f, 0x56, 0xf9, 0xa9, 0xb4, 0x6a, 0x25, 0x87, 0x5e,
	0x5c, 0xa9, 0xb5, 0x2a, 0x2c, 0x45, 0xea, 0xb1, 0xb9, 0xd4, 0x39, 0xa4, 0xaa, 0x38, 0xf4, 0xd2,
	0x03, 0x5a, 0xc3, 0xa8, 0x46, 0xb1, 0xd9, 0x0d, 0x8b, 0x91, 0x72, 0xef, 0x07, 0xea, 0x47, 0xac,
	0x98, 0x5d, 0xc2, 0xd6, 0xee, 0x8d, 0x79, 0xf3, 0x1e, 0xb3, 0x8f, 0x37, 0x0b, 0xcc, 0xf6, 0xa8,
	0x14, 0xff, 0x89, 0x4b, 0x59, 0x89, 0x5a, 0xb0, 0x21, 0x97, 0xc5, 0x2b, 0xd8, 0x8b, 0xc6, 0x00,
	0xd1, 0x6f, 0x07, 0x26, 0x6b, 0xe4, 0x39, 0x56, 0x2c, 0x04, 0xb7, 0xc1, 0x4a, 0x15, 0xa2, 0x0c,
	0x9d, 0xb9, 0xb3, 0x98, 0x25, 0x5d, 0xc9, 0xae, 0x60, 0x5c, 0x8b, 0x07, 0x2c, 0xc3, 0xff, 0xe6,
	0xce, 0x62, 0x9a, 0xe8, 0x82, 0x5d, 0xc3, 0x34, 0xdb, 0x15, 0x58, 0xd6, 0x69, 0x29, 0xca, 0x0c,
	0xc3, 0x21, 0x35, 0x03, 0x8d, 0x7d, 0x6d, 0xa1, 0x96, 0xa2, 0xb0, 0x6a, 0xb0, 0x32, 0x94, 0x91,
	0xa6, 0x68, 0x4c, 0x53, 0x18, 0x8c, 0xb6, 0x7b, 0x9e, 0x85, 0x63, 0x6a, 0xd1, 0x33, 0x7b, 0x0d,
	0x3e, 0x96, 0x59, 0xf5, 0x24, 0x6b, 0xcc, 0xc3, 0xc9, 0xdc, 0x59, 0x78, 0x49, 0x0f, 0x44, 0xbf,
	0x46, 0xe0, 0xde, 0x6b, 0x57, 0xec, 0x2d, 0x4c, 0xb6, 0x74, 0x7a, 0x3a, 0x72, 0x10, 0x07, 0x4b,
	0x2e, 0x8b, 0xa5, 0x36, 0x94, 0x98, 0x16, 0xbb, 0x86, 0x00, 0xcb, 0x2c, 0x95, 0xfc, 0x69, 0x27,
	0x78, 0xae, 0x4d, 0xac, 0x07, 0x09, 0x60, 0x99, 0x7d, 0xd3, 0x18, 0xfb, 0x00, 0x1e, 0x3f, 0xd4,
	0xdb, 0xb4, 0xc2, 0x47, 0xf2, 0x11, 0xc4, 0x17, 0xf4, 0xa6, 0xcf, 0x87, 0x7a, 0x9b, 0xe0, 0xe3,
	0x01, 0x55, 0xbd, 0x1e, 0x24, 0x2e, 0xd7, 0x25, 0xfb, 0x08, 0xbe, 0xa1, 0x2b, 0x49, 0xa6, 0x82,
	0xf8, 0xd2, 0xe2, 0x2b, 0x29, 0x4a, 0x85, 0xeb, 0x41, 0xe2, 0x71, 0x53, 0x77, 0x8a, 0x98, 0x26,
	0x8c, 0x8f, 0x14, 0x71, 0x3f, 0x82, 0x14, 0x6d, 0xcd, 0x56, 0x00, 0x9d, 0x42, 0x49, 0xfa, 0x0a,
	0x41, 0xcc, 0x6c, 0xc9, 0xf3, 0x14, 0x9f, 0x77, 0x00, 0xbb, 0x81, 0xd9, 0x9e, 0x3f, 0x60, 0xda,
	0x26, 0x4c, 0xa3, 0x5c, 0xcb, 0xcc, 0xbd, 0x68, 0xb0, 0x9f, 0x14, 0xb4, 0x44, 0x03, 0xb1, 0x4f,
	0x70, 0x66, 0xeb, 0x94, 0x0c, 0x3d, 0xeb, 0x8c, 0x9a, 0xf5, 0x3c, 0x6f, 0xda, 0x2b, 0x95, 0x64,
	0x2b, 0xf0, 0x37, 0x82, 0x57, 0x39, 0x8d, 0xf3, 0x49, 0x75, 0x45, 0xaa, 0x2f, 0x58, 0xdf, 0xb6,
	0x0d, 0xcb, 0xdc, 0xc6, 0xd4, 0xec, 0x06, 0xa0, 0x13, 0x29, 0x19, 0x02, 0xa9, 0xfe, 0x3f, 0x52,
	0xf5, 0xfe, 0x36, 0x1d, 0x70, 0xeb, 0x83, 0x6b, 0x62, 0x8c, 0xee, 0x20, 0xb0, 0xd2, 0x39, 0xd9,
	0x46, 0xe7, 0x74, 0x1b, 0x5f, 0x80, 0x7b, 0x50, 0x58, 0xa5, 0x85, 0xde, 0x01, 0x3f, 0x99, 0xb4,
	0xe5, 0x5d, 0x1e, 0xfd, 0x80, 0xa9, 0x1d, 0xdc, 0xc9, 0xda, 0x3a, 0xff, 0x5c, 0x5b, 0xc5, 0x77,
	0xb5, 0xb9, 0x11, 0xf4, 0xdc, 0x5f, 0x93, 0xa1, 0x75, 0x4d, 0xa2, 0x33, 0xfd, 0xf2, 0x2e, 0xe3,
	0xe8, 0x1c, 0x66, 0x7f, 0x05, 0x18, 0xbd, 0x87, 0xc0, 0x4a, 0x86, 0xbd, 0x81, 0x51, 0x9b, 0x82,
	0x59, 0x68, 0xbf, 0x0f, 0x80, 0xe0, 0xe8, 0x1d, 0x4c, 0xed, 0x38, 0xd8, 0x4b, 0xf0, 0x0a, 0x95,
	0x36, 0x7c, 0x57, 0xe4, 0x24, 0xf1, 0x12, 0xb7, 0x50, 0xdf, 0xdb, 0x32, 0xba, 0x84, 0xf3, 0xa3,
	0x0c, 0x22, 0x06, 0x17, 0xc7, 0x1f, 0x78, 0x33, 0xa1, 0x3f, 0xc1, 0xea, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xf8, 0x35, 0x81, 0x37, 0x2b, 0x04, 0x00, 0x00,
}
