// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InvalidRequest_Code int32

const (
	InvalidRequest_UNKNOWN_ERROR     InvalidRequest_Code = 0
	InvalidRequest_AUTH_ERROR        InvalidRequest_Code = 1
	InvalidRequest_WAS_RESPONSE      InvalidRequest_Code = 2
	InvalidRequest_MALFORMED_REQUEST InvalidRequest_Code = 3
	InvalidRequest_INCOMPATIBLE      InvalidRequest_Code = 4
	InvalidRequest_TOKEN_EXPIRED     InvalidRequest_Code = 5
)

var InvalidRequest_Code_name = map[int32]string{
	0: "UNKNOWN_ERROR",
	1: "AUTH_ERROR",
	2: "WAS_RESPONSE",
	3: "MALFORMED_REQUEST",
	4: "INCOMPATIBLE",
	5: "TOKEN_EXPIRED",
}
var InvalidRequest_Code_value = map[string]int32{
	"UNKNOWN_ERROR":     0,
	"AUTH_ERROR":        1,
	"WAS_RESPONSE":      2,
	"MALFORMED_REQUEST": 3,
	"INCOMPATIBLE":      4,
	"TOKEN_EXPIRED":     5,
}

func (x InvalidRequest_Code) String() string {
	return proto.EnumName(InvalidRequest_Code_name, int32(x))
}
func (InvalidRequest_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_message_b8617a1b851da78b, []int{2, 0}
}

type Header struct {
	Version              uint32   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Token                []byte   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ReqId                uint32   `protobuf:"varint,3,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	ClientNonce          []byte   `protobuf:"bytes,4,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"`
	ServerNonce          []byte   `protobuf:"bytes,5,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	Hmac                 []byte   `protobuf:"bytes,6,opt,name=hmac,proto3" json:"hmac,omitempty"`
	Encrypted            bool     `protobuf:"varint,7,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_b8617a1b851da78b, []int{0}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (dst *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(dst, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Header) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *Header) GetReqId() uint32 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *Header) GetClientNonce() []byte {
	if m != nil {
		return m.ClientNonce
	}
	return nil
}

func (m *Header) GetServerNonce() []byte {
	if m != nil {
		return m.ServerNonce
	}
	return nil
}

func (m *Header) GetHmac() []byte {
	if m != nil {
		return m.Hmac
	}
	return nil
}

func (m *Header) GetEncrypted() bool {
	if m != nil {
		return m.Encrypted
	}
	return false
}

type Message struct {
	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*Message_EncPayload
	//	*Message_InvalidReq
	//	*Message_AuthReq
	//	*Message_AuthResp
	//	*Message_GameReq
	//	*Message_GameResp
	Payload              isMessage_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_b8617a1b851da78b, []int{1}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_EncPayload struct {
	EncPayload []byte `protobuf:"bytes,2,opt,name=enc_payload,json=encPayload,proto3,oneof"`
}
type Message_InvalidReq struct {
	InvalidReq *InvalidRequest `protobuf:"bytes,3,opt,name=invalid_req,json=invalidReq,proto3,oneof"`
}
type Message_AuthReq struct {
	AuthReq *AuthRequest `protobuf:"bytes,4,opt,name=auth_req,json=authReq,proto3,oneof"`
}
type Message_AuthResp struct {
	AuthResp *AuthResponse `protobuf:"bytes,5,opt,name=auth_resp,json=authResp,proto3,oneof"`
}
type Message_GameReq struct {
	GameReq *GameRequest `protobuf:"bytes,6,opt,name=game_req,json=gameReq,proto3,oneof"`
}
type Message_GameResp struct {
	GameResp *GameResponse `protobuf:"bytes,7,opt,name=game_resp,json=gameResp,proto3,oneof"`
}

func (*Message_EncPayload) isMessage_Payload() {}
func (*Message_InvalidReq) isMessage_Payload() {}
func (*Message_AuthReq) isMessage_Payload()    {}
func (*Message_AuthResp) isMessage_Payload()   {}
func (*Message_GameReq) isMessage_Payload()    {}
func (*Message_GameResp) isMessage_Payload()   {}

func (m *Message) GetPayload() isMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Message) GetEncPayload() []byte {
	if x, ok := m.GetPayload().(*Message_EncPayload); ok {
		return x.EncPayload
	}
	return nil
}

func (m *Message) GetInvalidReq() *InvalidRequest {
	if x, ok := m.GetPayload().(*Message_InvalidReq); ok {
		return x.InvalidReq
	}
	return nil
}

func (m *Message) GetAuthReq() *AuthRequest {
	if x, ok := m.GetPayload().(*Message_AuthReq); ok {
		return x.AuthReq
	}
	return nil
}

func (m *Message) GetAuthResp() *AuthResponse {
	if x, ok := m.GetPayload().(*Message_AuthResp); ok {
		return x.AuthResp
	}
	return nil
}

func (m *Message) GetGameReq() *GameRequest {
	if x, ok := m.GetPayload().(*Message_GameReq); ok {
		return x.GameReq
	}
	return nil
}

func (m *Message) GetGameResp() *GameResponse {
	if x, ok := m.GetPayload().(*Message_GameResp); ok {
		return x.GameResp
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_OneofMarshaler, _Message_OneofUnmarshaler, _Message_OneofSizer, []interface{}{
		(*Message_EncPayload)(nil),
		(*Message_InvalidReq)(nil),
		(*Message_AuthReq)(nil),
		(*Message_AuthResp)(nil),
		(*Message_GameReq)(nil),
		(*Message_GameResp)(nil),
	}
}

func _Message_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message)
	// payload
	switch x := m.Payload.(type) {
	case *Message_EncPayload:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.EncPayload)
	case *Message_InvalidReq:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InvalidReq); err != nil {
			return err
		}
	case *Message_AuthReq:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AuthReq); err != nil {
			return err
		}
	case *Message_AuthResp:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AuthResp); err != nil {
			return err
		}
	case *Message_GameReq:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GameReq); err != nil {
			return err
		}
	case *Message_GameResp:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GameResp); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message.Payload has unexpected type %T", x)
	}
	return nil
}

func _Message_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message)
	switch tag {
	case 2: // payload.enc_payload
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Payload = &Message_EncPayload{x}
		return true, err
	case 3: // payload.invalid_req
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(InvalidRequest)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_InvalidReq{msg}
		return true, err
	case 4: // payload.auth_req
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AuthRequest)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_AuthReq{msg}
		return true, err
	case 5: // payload.auth_resp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AuthResponse)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_AuthResp{msg}
		return true, err
	case 6: // payload.game_req
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GameRequest)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_GameReq{msg}
		return true, err
	case 7: // payload.game_resp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GameResponse)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_GameResp{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message)
	// payload
	switch x := m.Payload.(type) {
	case *Message_EncPayload:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.EncPayload)))
		n += len(x.EncPayload)
	case *Message_InvalidReq:
		s := proto.Size(x.InvalidReq)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_AuthReq:
		s := proto.Size(x.AuthReq)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_AuthResp:
		s := proto.Size(x.AuthResp)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GameReq:
		s := proto.Size(x.GameReq)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GameResp:
		s := proto.Size(x.GameResp)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type InvalidRequest struct {
	Code                 InvalidRequest_Code `protobuf:"varint,1,opt,name=code,proto3,enum=api.InvalidRequest_Code" json:"code,omitempty"`
	Reason               string              `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *InvalidRequest) Reset()         { *m = InvalidRequest{} }
func (m *InvalidRequest) String() string { return proto.CompactTextString(m) }
func (*InvalidRequest) ProtoMessage()    {}
func (*InvalidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_b8617a1b851da78b, []int{2}
}
func (m *InvalidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidRequest.Unmarshal(m, b)
}
func (m *InvalidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidRequest.Marshal(b, m, deterministic)
}
func (dst *InvalidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidRequest.Merge(dst, src)
}
func (m *InvalidRequest) XXX_Size() int {
	return xxx_messageInfo_InvalidRequest.Size(m)
}
func (m *InvalidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidRequest proto.InternalMessageInfo

func (m *InvalidRequest) GetCode() InvalidRequest_Code {
	if m != nil {
		return m.Code
	}
	return InvalidRequest_UNKNOWN_ERROR
}

func (m *InvalidRequest) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterType((*Header)(nil), "api.Header")
	proto.RegisterType((*Message)(nil), "api.Message")
	proto.RegisterType((*InvalidRequest)(nil), "api.InvalidRequest")
	proto.RegisterEnum("api.InvalidRequest_Code", InvalidRequest_Code_name, InvalidRequest_Code_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_b8617a1b851da78b) }

var fileDescriptor_message_b8617a1b851da78b = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x4f, 0x8f, 0xd2, 0x40,
	0x18, 0xc6, 0xb7, 0x50, 0x0a, 0xbc, 0x05, 0x52, 0x46, 0xd7, 0x34, 0x1b, 0x0f, 0x2c, 0x5e, 0x38,
	0x28, 0x31, 0x98, 0x78, 0x67, 0x77, 0xab, 0x90, 0x5d, 0x5a, 0x1c, 0x20, 0xeb, 0xad, 0x19, 0xdb,
	0x37, 0xd0, 0x08, 0x6d, 0xe9, 0x14, 0xcc, 0x7e, 0x42, 0x8f, 0xde, 0xfc, 0x3c, 0x66, 0xfe, 0xac,
	0x60, 0xe2, 0xad, 0xcf, 0x33, 0xbf, 0x77, 0x9e, 0x3c, 0x6f, 0x07, 0xda, 0x3b, 0xe4, 0x9c, 0xad,
	0x71, 0x98, 0x17, 0x59, 0x99, 0x91, 0x2a, 0xcb, 0x93, 0x2b, 0x60, 0x87, 0x72, 0xa3, 0x8c, 0x2b,
	0x58, 0xb3, 0x9d, 0x3e, 0xec, 0xff, 0x34, 0xc0, 0x9a, 0x20, 0x8b, 0xb1, 0x20, 0x2e, 0xd4, 0x8f,
	0x58, 0xf0, 0x24, 0x4b, 0x5d, 0xa3, 0x67, 0x0c, 0xda, 0xf4, 0x59, 0x92, 0x97, 0x50, 0x2b, 0xb3,
	0xef, 0x98, 0xba, 0x95, 0x9e, 0x31, 0x68, 0x51, 0x25, 0xc8, 0x25, 0x58, 0x05, 0xee, 0xc3, 0x24,
	0x76, 0xab, 0x12, 0xaf, 0x15, 0xb8, 0x9f, 0xc6, 0xe4, 0x1a, 0x5a, 0xd1, 0x36, 0xc1, 0xb4, 0x0c,
	0xd3, 0x2c, 0x8d, 0xd0, 0x35, 0xe5, 0x8c, 0xad, 0x3c, 0x5f, 0x58, 0x02, 0xe1, 0x58, 0x1c, 0xb1,
	0xd0, 0x48, 0x4d, 0x21, 0xca, 0x53, 0x08, 0x01, 0x73, 0xb3, 0x63, 0x91, 0x6b, 0xc9, 0x23, 0xf9,
	0x4d, 0x5e, 0x43, 0x13, 0xd3, 0xa8, 0x78, 0xca, 0x4b, 0x8c, 0xdd, 0x7a, 0xcf, 0x18, 0x34, 0xe8,
	0xc9, 0xe8, 0xff, 0xae, 0x40, 0x7d, 0xa6, 0x8a, 0x93, 0x37, 0x60, 0x6d, 0x64, 0x29, 0xd9, 0xc4,
	0x1e, 0xd9, 0x43, 0x96, 0x27, 0x43, 0xd5, 0x93, 0xea, 0x23, 0x72, 0x0d, 0x36, 0xa6, 0x51, 0x98,
	0xb3, 0xa7, 0x6d, 0xc6, 0x62, 0xd5, 0x6d, 0x72, 0x41, 0x01, 0xd3, 0x68, 0xae, 0x3c, 0xf2, 0x11,
	0xec, 0x24, 0x3d, 0xb2, 0x6d, 0x12, 0x87, 0x05, 0xee, 0x65, 0x4f, 0x7b, 0xf4, 0x42, 0x5e, 0x36,
	0x55, 0x3e, 0xc5, 0xfd, 0x01, 0x79, 0x29, 0xe6, 0x92, 0xbf, 0x0e, 0x79, 0x07, 0x0d, 0xb1, 0x6f,
	0x39, 0x64, 0xca, 0x21, 0x47, 0x0e, 0x8d, 0x0f, 0xe5, 0xe6, 0x34, 0x51, 0x67, 0x4a, 0x92, 0xf7,
	0xd0, 0xd4, 0x38, 0xcf, 0xe5, 0x32, 0xec, 0x51, 0xf7, 0x8c, 0xe7, 0x79, 0x96, 0x72, 0x9c, 0x5c,
	0xd0, 0x06, 0xd3, 0x5a, 0x04, 0x88, 0x9f, 0x28, 0x03, 0xac, 0xb3, 0x80, 0xcf, 0x6c, 0x87, 0x67,
	0x01, 0x6b, 0x25, 0x45, 0x80, 0xc6, 0x79, 0x2e, 0x37, 0xf7, 0x1c, 0xa0, 0xf8, 0x53, 0xc0, 0x5a,
	0xeb, 0x9b, 0x26, 0xd4, 0xf5, 0x62, 0xfa, 0xbf, 0x0c, 0xe8, 0xfc, 0xdb, 0x96, 0xbc, 0x05, 0x33,
	0xca, 0x62, 0x94, 0xdb, 0xed, 0x8c, 0xdc, 0xff, 0x2c, 0x64, 0x78, 0x9b, 0xc5, 0x48, 0x25, 0x45,
	0x5e, 0x89, 0x87, 0xc2, 0x78, 0xa6, 0xde, 0x4f, 0x93, 0x6a, 0xd5, 0xff, 0x01, 0xa6, 0xa0, 0x48,
	0x17, 0xda, 0x2b, 0xff, 0xde, 0x0f, 0x1e, 0xfd, 0xd0, 0xa3, 0x34, 0xa0, 0xce, 0x05, 0xe9, 0x00,
	0x8c, 0x57, 0xcb, 0x89, 0xd6, 0x06, 0x71, 0xa0, 0xf5, 0x38, 0x5e, 0x84, 0xd4, 0x5b, 0xcc, 0x03,
	0x7f, 0xe1, 0x39, 0x15, 0x72, 0x09, 0xdd, 0xd9, 0xf8, 0xe1, 0x53, 0x40, 0x67, 0xde, 0x5d, 0x48,
	0xbd, 0x2f, 0x2b, 0x6f, 0xb1, 0x74, 0xaa, 0x02, 0x9c, 0xfa, 0xb7, 0xc1, 0x6c, 0x3e, 0x5e, 0x4e,
	0x6f, 0x1e, 0x3c, 0xc7, 0x14, 0xb7, 0x2f, 0x83, 0x7b, 0xcf, 0x0f, 0xbd, 0xaf, 0xf3, 0x29, 0xf5,
	0xee, 0x9c, 0xda, 0x37, 0x4b, 0xbe, 0xfd, 0x0f, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x32, 0xd0,
	0x69, 0x30, 0x29, 0x03, 0x00, 0x00,
}
