// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Header struct {
	Version              uint32   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Token                []byte   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ClientNonce          []byte   `protobuf:"bytes,3,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"`
	ServerNonce          []byte   `protobuf:"bytes,4,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	Hmac                 []byte   `protobuf:"bytes,5,opt,name=hmac,proto3" json:"hmac,omitempty"`
	Encrypted            bool     `protobuf:"varint,6,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_20a7564ed30363b6, []int{0}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (dst *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(dst, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Header) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *Header) GetClientNonce() []byte {
	if m != nil {
		return m.ClientNonce
	}
	return nil
}

func (m *Header) GetServerNonce() []byte {
	if m != nil {
		return m.ServerNonce
	}
	return nil
}

func (m *Header) GetHmac() []byte {
	if m != nil {
		return m.Hmac
	}
	return nil
}

func (m *Header) GetEncrypted() bool {
	if m != nil {
		return m.Encrypted
	}
	return false
}

type Message struct {
	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*Message_EncPayload
	//	*Message_AuthReq
	//	*Message_AuthResp
	//	*Message_Auth2Req
	//	*Message_Auth2Resp
	//	*Message_MakeMoveReq
	//	*Message_MakeMoveResp
	//	*Message_BoardReq
	//	*Message_BoardResp
	//	*Message_ListGamesReq
	//	*Message_ListGamesResp
	Payload              isMessage_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_20a7564ed30363b6, []int{1}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_EncPayload struct {
	EncPayload []byte `protobuf:"bytes,2,opt,name=enc_payload,json=encPayload,proto3,oneof"`
}
type Message_AuthReq struct {
	AuthReq *AuthRequest `protobuf:"bytes,3,opt,name=auth_req,json=authReq,proto3,oneof"`
}
type Message_AuthResp struct {
	AuthResp *AuthResponse `protobuf:"bytes,4,opt,name=auth_resp,json=authResp,proto3,oneof"`
}
type Message_Auth2Req struct {
	Auth2Req *Auth2Request `protobuf:"bytes,5,opt,name=auth2_req,json=auth2Req,proto3,oneof"`
}
type Message_Auth2Resp struct {
	Auth2Resp *Auth2Response `protobuf:"bytes,6,opt,name=auth2_resp,json=auth2Resp,proto3,oneof"`
}
type Message_MakeMoveReq struct {
	MakeMoveReq *MoveRequest `protobuf:"bytes,7,opt,name=make_move_req,json=makeMoveReq,proto3,oneof"`
}
type Message_MakeMoveResp struct {
	MakeMoveResp *MoveResponse `protobuf:"bytes,8,opt,name=make_move_resp,json=makeMoveResp,proto3,oneof"`
}
type Message_BoardReq struct {
	BoardReq *GetBoardRequest `protobuf:"bytes,9,opt,name=board_req,json=boardReq,proto3,oneof"`
}
type Message_BoardResp struct {
	BoardResp *GetBoardResponse `protobuf:"bytes,10,opt,name=board_resp,json=boardResp,proto3,oneof"`
}
type Message_ListGamesReq struct {
	ListGamesReq *ListGamesRequest `protobuf:"bytes,11,opt,name=list_games_req,json=listGamesReq,proto3,oneof"`
}
type Message_ListGamesResp struct {
	ListGamesResp *ListGamesResponse `protobuf:"bytes,12,opt,name=list_games_resp,json=listGamesResp,proto3,oneof"`
}

func (*Message_EncPayload) isMessage_Payload()    {}
func (*Message_AuthReq) isMessage_Payload()       {}
func (*Message_AuthResp) isMessage_Payload()      {}
func (*Message_Auth2Req) isMessage_Payload()      {}
func (*Message_Auth2Resp) isMessage_Payload()     {}
func (*Message_MakeMoveReq) isMessage_Payload()   {}
func (*Message_MakeMoveResp) isMessage_Payload()  {}
func (*Message_BoardReq) isMessage_Payload()      {}
func (*Message_BoardResp) isMessage_Payload()     {}
func (*Message_ListGamesReq) isMessage_Payload()  {}
func (*Message_ListGamesResp) isMessage_Payload() {}

func (m *Message) GetPayload() isMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Message) GetEncPayload() []byte {
	if x, ok := m.GetPayload().(*Message_EncPayload); ok {
		return x.EncPayload
	}
	return nil
}

func (m *Message) GetAuthReq() *AuthRequest {
	if x, ok := m.GetPayload().(*Message_AuthReq); ok {
		return x.AuthReq
	}
	return nil
}

func (m *Message) GetAuthResp() *AuthResponse {
	if x, ok := m.GetPayload().(*Message_AuthResp); ok {
		return x.AuthResp
	}
	return nil
}

func (m *Message) GetAuth2Req() *Auth2Request {
	if x, ok := m.GetPayload().(*Message_Auth2Req); ok {
		return x.Auth2Req
	}
	return nil
}

func (m *Message) GetAuth2Resp() *Auth2Response {
	if x, ok := m.GetPayload().(*Message_Auth2Resp); ok {
		return x.Auth2Resp
	}
	return nil
}

func (m *Message) GetMakeMoveReq() *MoveRequest {
	if x, ok := m.GetPayload().(*Message_MakeMoveReq); ok {
		return x.MakeMoveReq
	}
	return nil
}

func (m *Message) GetMakeMoveResp() *MoveResponse {
	if x, ok := m.GetPayload().(*Message_MakeMoveResp); ok {
		return x.MakeMoveResp
	}
	return nil
}

func (m *Message) GetBoardReq() *GetBoardRequest {
	if x, ok := m.GetPayload().(*Message_BoardReq); ok {
		return x.BoardReq
	}
	return nil
}

func (m *Message) GetBoardResp() *GetBoardResponse {
	if x, ok := m.GetPayload().(*Message_BoardResp); ok {
		return x.BoardResp
	}
	return nil
}

func (m *Message) GetListGamesReq() *ListGamesRequest {
	if x, ok := m.GetPayload().(*Message_ListGamesReq); ok {
		return x.ListGamesReq
	}
	return nil
}

func (m *Message) GetListGamesResp() *ListGamesResponse {
	if x, ok := m.GetPayload().(*Message_ListGamesResp); ok {
		return x.ListGamesResp
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_OneofMarshaler, _Message_OneofUnmarshaler, _Message_OneofSizer, []interface{}{
		(*Message_EncPayload)(nil),
		(*Message_AuthReq)(nil),
		(*Message_AuthResp)(nil),
		(*Message_Auth2Req)(nil),
		(*Message_Auth2Resp)(nil),
		(*Message_MakeMoveReq)(nil),
		(*Message_MakeMoveResp)(nil),
		(*Message_BoardReq)(nil),
		(*Message_BoardResp)(nil),
		(*Message_ListGamesReq)(nil),
		(*Message_ListGamesResp)(nil),
	}
}

func _Message_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message)
	// payload
	switch x := m.Payload.(type) {
	case *Message_EncPayload:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.EncPayload)
	case *Message_AuthReq:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AuthReq); err != nil {
			return err
		}
	case *Message_AuthResp:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AuthResp); err != nil {
			return err
		}
	case *Message_Auth2Req:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Auth2Req); err != nil {
			return err
		}
	case *Message_Auth2Resp:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Auth2Resp); err != nil {
			return err
		}
	case *Message_MakeMoveReq:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MakeMoveReq); err != nil {
			return err
		}
	case *Message_MakeMoveResp:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MakeMoveResp); err != nil {
			return err
		}
	case *Message_BoardReq:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BoardReq); err != nil {
			return err
		}
	case *Message_BoardResp:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BoardResp); err != nil {
			return err
		}
	case *Message_ListGamesReq:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ListGamesReq); err != nil {
			return err
		}
	case *Message_ListGamesResp:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ListGamesResp); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message.Payload has unexpected type %T", x)
	}
	return nil
}

func _Message_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message)
	switch tag {
	case 2: // payload.enc_payload
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Payload = &Message_EncPayload{x}
		return true, err
	case 3: // payload.auth_req
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AuthRequest)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_AuthReq{msg}
		return true, err
	case 4: // payload.auth_resp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AuthResponse)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_AuthResp{msg}
		return true, err
	case 5: // payload.auth2_req
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Auth2Request)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_Auth2Req{msg}
		return true, err
	case 6: // payload.auth2_resp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Auth2Response)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_Auth2Resp{msg}
		return true, err
	case 7: // payload.make_move_req
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MoveRequest)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_MakeMoveReq{msg}
		return true, err
	case 8: // payload.make_move_resp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MoveResponse)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_MakeMoveResp{msg}
		return true, err
	case 9: // payload.board_req
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetBoardRequest)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_BoardReq{msg}
		return true, err
	case 10: // payload.board_resp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetBoardResponse)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_BoardResp{msg}
		return true, err
	case 11: // payload.list_games_req
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ListGamesRequest)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_ListGamesReq{msg}
		return true, err
	case 12: // payload.list_games_resp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ListGamesResponse)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_ListGamesResp{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message)
	// payload
	switch x := m.Payload.(type) {
	case *Message_EncPayload:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.EncPayload)))
		n += len(x.EncPayload)
	case *Message_AuthReq:
		s := proto.Size(x.AuthReq)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_AuthResp:
		s := proto.Size(x.AuthResp)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Auth2Req:
		s := proto.Size(x.Auth2Req)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Auth2Resp:
		s := proto.Size(x.Auth2Resp)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_MakeMoveReq:
		s := proto.Size(x.MakeMoveReq)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_MakeMoveResp:
		s := proto.Size(x.MakeMoveResp)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_BoardReq:
		s := proto.Size(x.BoardReq)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_BoardResp:
		s := proto.Size(x.BoardResp)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ListGamesReq:
		s := proto.Size(x.ListGamesReq)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ListGamesResp:
		s := proto.Size(x.ListGamesResp)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Header)(nil), "api.Header")
	proto.RegisterType((*Message)(nil), "api.Message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_20a7564ed30363b6) }

var fileDescriptor_message_20a7564ed30363b6 = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x93, 0xc1, 0x6a, 0xdb, 0x40,
	0x10, 0x86, 0xad, 0x26, 0xb6, 0xac, 0x91, 0x9c, 0xb6, 0x43, 0x5a, 0x44, 0xe8, 0xc1, 0x49, 0x2f,
	0xbe, 0xd4, 0x14, 0x19, 0x02, 0x3d, 0x14, 0xda, 0x5c, 0xe2, 0x43, 0x53, 0x8a, 0x5e, 0x40, 0xac,
	0xe5, 0x21, 0x16, 0x91, 0xb4, 0x1b, 0xed, 0xda, 0x90, 0x07, 0xe8, 0xfb, 0xf4, 0x11, 0x8b, 0x66,
	0x25, 0x6b, 0xe3, 0x9b, 0xe7, 0x9f, 0xff, 0xf3, 0xbf, 0xff, 0xb2, 0x82, 0x59, 0x45, 0x5a, 0x8b,
	0x47, 0x5a, 0xaa, 0x46, 0x1a, 0x89, 0x67, 0x42, 0x15, 0x57, 0x20, 0xf6, 0x66, 0x67, 0x85, 0x2b,
	0x78, 0x14, 0x55, 0xb7, 0xbc, 0xf9, 0xe7, 0xc1, 0x64, 0x4d, 0x62, 0x4b, 0x0d, 0xc6, 0xe0, 0x1f,
	0xa8, 0xd1, 0x85, 0xac, 0x63, 0x6f, 0xee, 0x2d, 0x66, 0x69, 0x3f, 0xe2, 0x25, 0x8c, 0x8d, 0x7c,
	0xa2, 0x3a, 0x7e, 0x33, 0xf7, 0x16, 0x51, 0x6a, 0x07, 0xbc, 0x86, 0x28, 0x2f, 0x0b, 0xaa, 0x4d,
	0x56, 0xcb, 0x3a, 0xa7, 0xf8, 0x8c, 0x97, 0xa1, 0xd5, 0x7e, 0xb7, 0x52, 0x6b, 0xd1, 0xd4, 0x1c,
	0xa8, 0xe9, 0x2c, 0xe7, 0xd6, 0x62, 0x35, 0x6b, 0x41, 0x38, 0xdf, 0x55, 0x22, 0x8f, 0xc7, 0xbc,
	0xe2, 0xdf, 0xf8, 0x09, 0x02, 0xaa, 0xf3, 0xe6, 0x45, 0x19, 0xda, 0xc6, 0x93, 0xb9, 0xb7, 0x98,
	0xa6, 0x83, 0x70, 0xf3, 0x77, 0x0c, 0xfe, 0x83, 0x6d, 0x88, 0x9f, 0x61, 0xb2, 0xe3, 0xd3, 0xf3,
	0x91, 0xc3, 0x24, 0x5c, 0x0a, 0x55, 0x2c, 0x6d, 0xa1, 0xb4, 0x5b, 0xe1, 0x35, 0x84, 0x54, 0xe7,
	0x99, 0x12, 0x2f, 0xa5, 0x14, 0x5b, 0x5b, 0x62, 0x3d, 0x4a, 0x81, 0xea, 0xfc, 0x8f, 0xd5, 0xf0,
	0x0b, 0x4c, 0xdb, 0x0b, 0xca, 0x1a, 0x7a, 0xe6, 0x1e, 0x61, 0xf2, 0x8e, 0xff, 0xe9, 0xe7, 0xde,
	0xec, 0x52, 0x7a, 0xde, 0x93, 0x36, 0xeb, 0x51, 0xea, 0x0b, 0x3b, 0xe2, 0x57, 0x08, 0x3a, 0xbb,
	0x56, 0x5c, 0x2a, 0x4c, 0xde, 0x3b, 0x7e, 0xad, 0x64, 0xad, 0x69, 0x3d, 0x4a, 0xa7, 0xa2, 0x9b,
	0x7b, 0x22, 0xe1, 0x84, 0xf1, 0x09, 0x91, 0x0c, 0x11, 0x4c, 0xb4, 0x33, 0xae, 0x00, 0x7a, 0x42,
	0x2b, 0xbe, 0x85, 0x30, 0x41, 0x17, 0x39, 0xa6, 0x04, 0xa2, 0x17, 0xf0, 0x16, 0x66, 0x95, 0x78,
	0xa2, 0xac, 0x92, 0x07, 0xe2, 0x28, 0xdf, 0x29, 0xf3, 0x20, 0x0f, 0x34, 0x24, 0x85, 0xad, 0xb1,
	0x93, 0xf0, 0x1b, 0x5c, 0xb8, 0x9c, 0x56, 0xf1, 0xd4, 0x39, 0xa3, 0x75, 0x1d, 0xf3, 0xa2, 0x81,
	0xd4, 0x0a, 0x57, 0x10, 0x6c, 0xa4, 0x68, 0xb6, 0x1c, 0x17, 0x30, 0x75, 0xc9, 0xd4, 0x3d, 0x99,
	0xbb, 0x76, 0xe1, 0x94, 0xdb, 0x74, 0x33, 0xde, 0x02, 0xf4, 0x90, 0x56, 0x31, 0x30, 0xf5, 0xe1,
	0x84, 0x1a, 0xfa, 0x6d, 0x7a, 0x01, 0xbf, 0xc3, 0x45, 0x59, 0x68, 0x93, 0xb5, 0x2f, 0x58, 0x73,
	0x62, 0xe8, 0xb0, 0xbf, 0x0a, 0x6d, 0xee, 0xdb, 0xcd, 0x10, 0x19, 0x95, 0x8e, 0x86, 0x3f, 0xe0,
	0xed, 0x2b, 0x5c, 0xab, 0x38, 0x62, 0xfe, 0xe3, 0x29, 0x7f, 0x0c, 0x9f, 0x95, 0xae, 0x78, 0x17,
	0x80, 0xdf, 0xbd, 0xa3, 0xcd, 0x84, 0xbf, 0xa0, 0xd5, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xee,
	0xda, 0x23, 0x02, 0x6f, 0x03, 0x00, 0x00,
}
