// Code generated by protoc-gen-go. DO NOT EDIT.
// source: move.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Move_Castle int32

const (
	Move_NONE      Move_Castle = 0
	Move_KINGSIDE  Move_Castle = 1
	Move_QUEENSIDE Move_Castle = 2
)

var Move_Castle_name = map[int32]string{
	0: "NONE",
	1: "KINGSIDE",
	2: "QUEENSIDE",
}
var Move_Castle_value = map[string]int32{
	"NONE":      0,
	"KINGSIDE":  1,
	"QUEENSIDE": 2,
}

func (x Move_Castle) String() string {
	return proto.EnumName(Move_Castle_name, int32(x))
}
func (Move_Castle) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_move_d179a2073b6cd758, []int{0, 0}
}

type Move struct {
	Type                 Type        `protobuf:"varint,1,opt,name=type,proto3,enum=api.Type" json:"type,omitempty"`
	Start                *Position   `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  *Position   `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	Promotion            bool        `protobuf:"varint,4,opt,name=promotion,proto3" json:"promotion,omitempty"`
	Castle               Move_Castle `protobuf:"varint,5,opt,name=castle,proto3,enum=api.Move_Castle" json:"castle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Move) Reset()         { *m = Move{} }
func (m *Move) String() string { return proto.CompactTextString(m) }
func (*Move) ProtoMessage()    {}
func (*Move) Descriptor() ([]byte, []int) {
	return fileDescriptor_move_d179a2073b6cd758, []int{0}
}
func (m *Move) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Move.Unmarshal(m, b)
}
func (m *Move) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Move.Marshal(b, m, deterministic)
}
func (dst *Move) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Move.Merge(dst, src)
}
func (m *Move) XXX_Size() int {
	return xxx_messageInfo_Move.Size(m)
}
func (m *Move) XXX_DiscardUnknown() {
	xxx_messageInfo_Move.DiscardUnknown(m)
}

var xxx_messageInfo_Move proto.InternalMessageInfo

func (m *Move) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_PAWN
}

func (m *Move) GetStart() *Position {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Move) GetEnd() *Position {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *Move) GetPromotion() bool {
	if m != nil {
		return m.Promotion
	}
	return false
}

func (m *Move) GetCastle() Move_Castle {
	if m != nil {
		return m.Castle
	}
	return Move_NONE
}

func init() {
	proto.RegisterType((*Move)(nil), "api.Move")
	proto.RegisterEnum("api.Move_Castle", Move_Castle_name, Move_Castle_value)
}

func init() { proto.RegisterFile("move.proto", fileDescriptor_move_d179a2073b6cd758) }

var fileDescriptor_move_d179a2073b6cd758 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xcf, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0x71, 0xb3, 0x76, 0xa5, 0x3d, 0x6e, 0x52, 0xce, 0x55, 0x10, 0xc5, 0x32, 0x6f, 0x7a,
	0x15, 0x61, 0x3e, 0x82, 0x06, 0x19, 0x62, 0xd4, 0xa8, 0x0f, 0x10, 0x67, 0x2e, 0x02, 0xa6, 0x27,
	0xb4, 0x61, 0xd0, 0xf7, 0xf5, 0x41, 0xa4, 0xa9, 0xe0, 0xcd, 0x2e, 0xf3, 0xfb, 0x87, 0xf0, 0x05,
	0xc0, 0xd3, 0xc1, 0x8a, 0xd0, 0x53, 0x24, 0xcc, 0x4c, 0x70, 0xe7, 0xab, 0x3d, 0x79, 0x4f, 0xdd,
	0x4c, 0x9b, 0x1f, 0x06, 0xf9, 0x13, 0x1d, 0x2c, 0x5e, 0x42, 0x1e, 0xc7, 0x60, 0x39, 0x6b, 0x58,
	0x7b, 0xb6, 0xad, 0x84, 0x09, 0x4e, 0xbc, 0x8f, 0xc1, 0xea, 0xc4, 0x78, 0x0d, 0xcb, 0x21, 0x9a,
	0x3e, 0xf2, 0x45, 0xc3, 0xda, 0xd3, 0xed, 0x3a, 0xf5, 0x17, 0x1a, 0x5c, 0x74, 0xd4, 0xe9, 0xb9,
	0xe1, 0x15, 0x64, 0xb6, 0xfb, 0xe2, 0xd9, 0xb1, 0x2b, 0x53, 0xc1, 0x0b, 0xa8, 0x42, 0x4f, 0x9e,
	0x26, 0xe1, 0x79, 0xc3, 0xda, 0x52, 0xff, 0x03, 0xb6, 0x50, 0xec, 0xcd, 0x10, 0xbf, 0x2d, 0x5f,
	0xa6, 0x11, 0x75, 0x7a, 0x61, 0x5a, 0x27, 0xee, 0x92, 0xeb, 0xbf, 0xbe, 0xb9, 0x81, 0x62, 0x16,
	0x2c, 0x21, 0x57, 0xcf, 0x4a, 0xd6, 0x27, 0xb8, 0x82, 0xf2, 0x71, 0xa7, 0x1e, 0xde, 0x76, 0xf7,
	0xb2, 0x66, 0xb8, 0x86, 0xea, 0xf5, 0x43, 0x4a, 0x95, 0x8e, 0x8b, 0xcf, 0x22, 0xfd, 0xf6, 0xf6,
	0x37, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xbb, 0x3b, 0x29, 0x0e, 0x01, 0x00, 0x00,
}
